export const GROUP_1 = [
  {
    word: "abound",
    meaning: "be present in large quantities",
    partOfSpeech: "Verb",
    examples: [
      "Wildlife abounds in this untouched forest.",
      "Opportunities abound for skilled workers in this industry.",
    ],
    antonyms: ["lack", "want"],
    synonyms: ["teem", "overflow"],
  },
  {
    word: "amorphous",
    meaning: "lacking structure; unclear",
    partOfSpeech: "Adjective",
    examples: [
      "The amorphous cloud of gas slowly took shape.",
      "Her amorphous career path made it hard to define her expertise.",
    ],
    antonyms: ["structured", "defined"],
    synonyms: ["shapeless", "formless"],
  },
  {
    word: "austere",
    meaning: "(of a person) strict and stern in character",
    partOfSpeech: "Adjective",
    examples: [
      "The austere teacher tolerated no nonsense in her classroom.",
      "His austere demeanor made him seem unapproachable.",
    ],
    antonyms: ["indulgent", "lenient"],
    synonyms: ["severe", "stern"],
  },
  {
    word: "austere",
    meaning: "(of living conditions) lacking luxury; extremely harsh",
    partOfSpeech: "Adjective",
    examples: [
      "The monks lived in austere conditions with minimal possessions.",
      "The prison cell was austere, containing only a cot and toilet.",
    ],
    antonyms: ["luxurious", "opulent"],
    synonyms: ["spartan", "ascetic"],
  },
  {
    word: "belie",
    meaning: "give a false impression of; mask",
    partOfSpeech: "Verb",
    examples: [
      "His calm voice belied the anger he felt inside.",
      "The cheerful decor belied the building's troubled history.",
    ],
    antonyms: ["reveal", "expose"],
    synonyms: ["misrepresent", "disguise"],
  },
  {
    word: "capricious",
    meaning: "having varying moods; fickle",
    partOfSpeech: "Adjective",
    examples: [
      "The capricious weather changed from sunny to stormy in minutes.",
      "Dealing with a capricious boss required constant adaptation.",
    ],
    antonyms: ["consistent", "steady"],
    synonyms: ["mercurial", "temperamental"],
  },
  {
    word: "cerebral",
    meaning: "related to the brain",
    partOfSpeech: "Adjective",
    examples: [
      "The cerebral hemorrhage required immediate medical attention.",
      "Doctors studied the cerebral activity during the experiment.",
    ],
    antonyms: ["physical", "bodily"],
    synonyms: ["neural", "intellectual"],
  },
  {
    word: "cerebral",
    meaning: "intellectual; focused on learning rather than emotion",
    partOfSpeech: "Adjective",
    examples: [
      "She preferred cerebral puzzles over physical challenges.",
      "The film was too cerebral for mainstream audiences.",
    ],
    antonyms: ["emotional", "instinctive"],
    synonyms: ["thoughtful", "highbrow"],
  },
  {
    word: "congenial",
    meaning:
      "(of a person) likable and friendly, often due to shared interests",
    partOfSpeech: "Adjective",
    examples: [
      "We found our new neighbors to be quite congenial.",
      "The congenial professor made learning enjoyable.",
    ],
    antonyms: ["unfriendly", "disagreeable"],
    synonyms: ["amicable", "affable"],
  },
  {
    word: "congenial",
    meaning: "(of a thing) enjoyable because it aligns with one's tendencies",
    partOfSpeech: "Adjective",
    examples: [
      "The quiet café provided a congenial atmosphere for writing.",
      "He found the company's values congenial to his own.",
    ],
    antonyms: ["inhospitable", "unpleasant"],
    synonyms: ["compatible", "agreeable"],
  },
  {
    word: "conspicuous",
    meaning: "easily noticed; obvious",
    partOfSpeech: "Adjective",
    examples: [
      "Her bright red coat made her conspicuous in the crowd.",
      "There was a conspicuous absence of managers at the meeting.",
    ],
    antonyms: ["inconspicuous", "unnoticeable"],
    synonyms: ["prominent", "obvious"],
  },
  {
    word: "cursory",
    meaning: "lacking effort; without care",
    partOfSpeech: "Adjective",
    examples: [
      "He gave the report only a cursory glance before signing.",
      "The cursory inspection missed several safety violations.",
    ],
    antonyms: ["thorough", "detailed"],
    synonyms: ["perfunctory", "superficial"],
  },
  {
    word: "daunting",
    meaning: "scary or frightening; (of a task) seeming impossible",
    partOfSpeech: "Adjective",
    examples: [
      "The sheer size of the project was daunting.",
      "Facing the champion boxer seemed a daunting prospect.",
    ],
    antonyms: ["encouraging", "reassuring"],
    synonyms: ["intimidating", "formidable"],
  },
  {
    word: "deify",
    meaning: "look up to someone or something as a god",
    partOfSpeech: "Verb",
    examples: [
      "Some fans deify their favorite celebrities.",
      "Ancient cultures would often deify natural phenomena.",
    ],
    antonyms: ["vilify", "demean"],
    synonyms: ["idolize", "worship"],
  },
  {
    word: "didactic",
    meaning:
      "meant for teaching; educational, sometimes in a condescending manner",
    partOfSpeech: "Adjective",
    examples: [
      "The fable had a clear didactic purpose about honesty.",
      "Her didactic tone made the students feel patronized.",
    ],
    antonyms: ["uninstructive", "nondidactic"],
    synonyms: ["pedagogical", "preachy"],
  },
  {
    word: "disseminate",
    meaning: "distribute or circulate broadly",
    partOfSpeech: "Verb",
    examples: [
      "The organization works to disseminate health information.",
      "Social media helps disseminate news quickly.",
    ],
    antonyms: ["withhold", "suppress"],
    synonyms: ["spread", "circulate"],
  },
  {
    word: "feasible",
    meaning: "likely to be achieved; practical",
    partOfSpeech: "Adjective",
    examples: [
      "The construction plan seems feasible within our budget.",
      "Is it feasible to complete this project by Friday?",
    ],
    antonyms: ["impossible", "impractical"],
    synonyms: ["viable", "workable"],
  },
  {
    word: "flout",
    meaning: "break a rule without guilt",
    partOfSpeech: "Verb",
    examples: [
      "The company continued to flout environmental regulations.",
      "He openly flouted the dress code by wearing jeans.",
    ],
    antonyms: ["obey", "comply"],
    synonyms: ["defy", "disregard"],
  },
  {
    word: "homogeneous",
    meaning: "composed of similar parts; alike",
    partOfSpeech: "Adjective",
    examples: [
      "The neighborhood was homogeneous, with nearly identical houses.",
      "The team lacked diversity, being homogeneous in background.",
    ],
    antonyms: ["diverse", "heterogeneous"],
    synonyms: ["uniform", "similar"],
  },
  {
    word: "humdrum",
    meaning: "boring; unlikely to excite",
    partOfSpeech: "Adjective",
    examples: [
      "She longed to escape her humdrum routine.",
      "The meeting was a humdrum affair with little discussion.",
    ],
    antonyms: ["exciting", "stimulating"],
    synonyms: ["mundane", "tedious"],
  },
  {
    word: "insipid",
    meaning: "without flavor; lacking energy",
    partOfSpeech: "Adjective",
    examples: [
      "The soup was insipid and needed more seasoning.",
      "His insipid presentation failed to engage the audience.",
    ],
    antonyms: ["flavorful", "exciting"],
    synonyms: ["bland", "vapid"],
  },
  {
    word: "loquacious",
    meaning: "likely to talk a lot; wordy",
    partOfSpeech: "Adjective",
    examples: [
      "The loquacious tour guide shared endless stories.",
      "Her loquacious nature made her perfect for radio.",
    ],
    antonyms: ["taciturn", "reticent"],
    synonyms: ["talkative", "verbose"],
  },
  {
    word: "misanthropic",
    meaning: "having a distaste for humans and society",
    partOfSpeech: "Adjective",
    examples: [
      "The misanthropic old man refused all visitors.",
      "His misanthropic views made him avoid crowded places.",
    ],
    antonyms: ["philanthropic", "sociable"],
    synonyms: ["antisocial", "cynical"],
  },
  {
    word: "misnomer",
    meaning: "a misleading or inaccurate name",
    partOfSpeech: "Noun",
    examples: [
      "'Fun Size' candy bars are a misnomer for such small portions.",
      "The 'common cold' is a misnomer since there are many viruses.",
    ],
    antonyms: ["apt name", "proper term"],
    synonyms: ["wrong name", "incorrect label"],
  },
  {
    word: "negligent",
    meaning: "lacking care or attention",
    partOfSpeech: "Adjective",
    examples: [
      "The negligent driver caused the accident.",
      "The landlord was negligent in maintaining the property.",
    ],
    antonyms: ["careful", "attentive"],
    synonyms: ["careless", "remiss"],
  },
  {
    word: "obsequious",
    meaning: "excessively submissive to authority",
    partOfSpeech: "Adjective",
    examples: [
      "The obsequious assistant agreed with everything the boss said.",
      "His obsequious behavior made his colleagues uncomfortable.",
    ],
    antonyms: ["assertive", "independent"],
    synonyms: ["servile", "sycophantic"],
  },
  {
    word: "placate",
    meaning: "decrease someone's anger or other negative emotion",
    partOfSpeech: "Verb",
    examples: [
      "The manager tried to placate the angry customer.",
      "They offered concessions to placate the protesters.",
    ],
    antonyms: ["aggravate", "provoke"],
    synonyms: ["appease", "mollify"],
  },
  {
    word: "proclivity",
    meaning: "a fondness or liking for something",
    partOfSpeech: "Noun",
    examples: [
      "She had a proclivity for spicy foods.",
      "His early proclivity for music led to a career in composition.",
    ],
    antonyms: ["aversion", "disinclination"],
    synonyms: ["inclination", "penchant"],
  },
  {
    word: "puerile",
    meaning: "immature and childish",
    partOfSpeech: "Adjective",
    examples: [
      "The puerile jokes were inappropriate for the meeting.",
      "His puerile behavior embarrassed his colleagues.",
    ],
    antonyms: ["mature", "sophisticated"],
    synonyms: ["juvenile", "infantile"],
  },
  {
    word: "quixotic",
    meaning: "excessively visionary; unfeasible",
    partOfSpeech: "Adjective",
    examples: [
      "His quixotic plan to end world hunger was unrealistic.",
      "The quixotic quest for perfection wasted valuable time.",
    ],
    antonyms: ["practical", "realistic"],
    synonyms: ["idealistic", "utopian"],
  },
  {
    word: "spendthrift",
    meaning: "someone who spends money recklessly",
    partOfSpeech: "Noun",
    examples: [
      "The spendthrift heir quickly wasted his inheritance.",
      "Her spendthrift habits left her constantly in debt.",
    ],
    antonyms: ["miser", "saver"],
    synonyms: ["prodigal", "wastrel"],
  },
  {
    word: "taciturn",
    meaning: "of few words; speaking little",
    partOfSpeech: "Adjective",
    examples: [
      "The taciturn cowboy rarely joined conversations.",
      "His taciturn nature made him seem mysterious.",
    ],
    antonyms: ["talkative", "loquacious"],
    synonyms: ["reticent", "reserved"],
  },
  {
    word: "wary",
    meaning: "exercising caution; careful",
    partOfSpeech: "Adjective",
    examples: [
      "Investors were wary of putting money into the new venture.",
      "She grew wary of strangers after the incident.",
    ],
    antonyms: ["heedless", "trusting"],
    synonyms: ["cautious", "vigilant"],
  },
];

export const GROUP_2 = [
  {
    word: "adulterate",
    meaning: "damage the quality of; corrupt",
    partOfSpeech: "Verb",
    examples: [
      "The company was fined for adulterating their products with cheap fillers.",
      "Adding water to milk adulterates its nutritional value.",
    ],
    synonyms: ["contaminate", "degrade", "taint"],
    antonyms: ["purify", "refine"],
  },
  {
    word: "advocate",
    meaning: "support; be in favor of",
    partOfSpeech: "Verb",
    examples: [
      "She advocates for better healthcare policies.",
      "The professor advocates using primary sources in research.",
    ],
    synonyms: ["support", "champion", "promote"],
    antonyms: ["oppose", "criticize"],
  },
  {
    word: "advocate",
    meaning: "someone who supports a cause, organization, or person",
    partOfSpeech: "Noun",
    examples: [
      "He works as a child advocate in family court.",
      "The environmental advocate spoke passionately about conservation.",
    ],
    synonyms: ["supporter", "proponent", "defender"],
    antonyms: ["opponent", "adversary"],
  },
  {
    word: "aggrandize",
    meaning: "enhance one's power or standing",
    partOfSpeech: "Verb",
    examples: [
      "The dictator sought to aggrandize himself through propaganda.",
      "She aggrandized her reputation by taking credit for others' work.",
    ],
    synonyms: ["exaggerate", "magnify", "elevate"],
    antonyms: ["diminish", "belittle"],
  },
  {
    word: "alacrity",
    meaning: "eagerness to do something",
    partOfSpeech: "Noun",
    examples: [
      "She accepted the challenge with alacrity.",
      "The staff responded with alacrity to the emergency situation.",
    ],
    synonyms: ["eagerness", "willingness", "readiness"],
    antonyms: ["reluctance", "hesitation"],
  },
  {
    word: "ambivalent",
    meaning: "having conflicting emotions; unsure",
    partOfSpeech: "Adjective",
    examples: [
      "I feel ambivalent about the job offer - it pays well but requires relocation.",
      "His ambivalent attitude made decision-making difficult.",
    ],
    synonyms: ["uncertain", "conflicted", "torn"],
    antonyms: ["decisive", "resolute"],
  },
  {
    word: "ameliorate",
    meaning: "improve a bad feeling or bad situation",
    partOfSpeech: "Verb",
    examples: [
      "The new policy ameliorated working conditions.",
      "Medication helped ameliorate her chronic pain.",
    ],
    synonyms: ["improve", "enhance", "relieve"],
    antonyms: ["worsen", "aggravate"],
  },
  {
    word: "amenable",
    meaning: "(of a person) receptive to change; open",
    partOfSpeech: "Adjective",
    examples: [
      "The team was amenable to trying the new strategy.",
      "She's generally amenable to constructive criticism.",
    ],
    synonyms: ["receptive", "open-minded", "agreeable"],
    antonyms: ["resistant", "uncooperative"],
  },
  {
    word: "amenable",
    meaning: "(of a thing) responsive to",
    partOfSpeech: "Adjective",
    examples: [
      "This material is amenable to various shaping techniques.",
      "The disease is amenable to treatment with antibiotics.",
    ],
    synonyms: ["responsive", "adaptable", "susceptible"],
    antonyms: ["immune", "resistant"],
  },
  {
    word: "anachronistic",
    meaning: "of the wrong time or era",
    partOfSpeech: "Adjective",
    examples: [
      "The film's depiction of smartphones in the 1920s was anachronistic.",
      "His views on gender roles seem anachronistic in modern society.",
    ],
    synonyms: ["outdated", "obsolete", "anachronous"],
    antonyms: ["timely", "contemporary"],
  },
  {
    word: "audacious",
    meaning: "bold; unafraid of risks",
    partOfSpeech: "Adjective",
    examples: [
      "Her audacious plan to climb the mountain alone succeeded.",
      "The startup made an audacious bid for the contract.",
    ],
    synonyms: ["bold", "daring", "fearless"],
    antonyms: ["timid", "cautious"],
  },
  {
    word: "audacious",
    meaning: "rude; exhibiting disrespect",
    partOfSpeech: "Adjective",
    examples: [
      "His audacious remarks offended many attendees.",
      "The student's audacious behavior disrupted the class.",
    ],
    synonyms: ["impudent", "brazen", "insolent"],
    antonyms: ["respectful", "courteous"],
  },
  {
    word: "avaricious",
    meaning: "greedy; always wanting more",
    partOfSpeech: "Adjective",
    examples: [
      "The avaricious CEO prioritized profits over employee welfare.",
      "His avaricious nature made him an unpopular business partner.",
    ],
    synonyms: ["greedy", "covetous", "rapacious"],
    antonyms: ["generous", "selfless"],
  },
  {
    word: "banal",
    meaning: "unoriginal and dull; lacking creativity",
    partOfSpeech: "Adjective",
    examples: [
      "The speech was full of banal platitudes.",
      "The movie's plot was banal and predictable.",
    ],
    synonyms: ["trite", "clichéd", "hackneyed"],
    antonyms: ["original", "inspired"],
  },
  {
    word: "benign",
    meaning: "harmless; having little effect",
    partOfSpeech: "Adjective",
    examples: [
      "The tumor turned out to be benign.",
      "The new law had a benign impact on small businesses.",
    ],
    synonyms: ["harmless", "mild", "innocuous"],
    antonyms: ["harmful", "malignant"],
  },
  {
    word: "benign",
    meaning: "(of a person's character) kind hearted; nice",
    partOfSpeech: "Adjective",
    examples: [
      "His benign smile put everyone at ease.",
      "The teacher had a benign approach to discipline.",
    ],
    synonyms: ["kind", "gentle", "benevolent"],
    antonyms: ["cruel", "hostile"],
  },
  {
    word: "brazen",
    meaning: "shameless and excessively forward",
    partOfSpeech: "Adjective",
    examples: [
      "She made a brazen attempt to cut in line.",
      "The brazen theft occurred in broad daylight.",
    ],
    synonyms: ["shameless", "bold", "impudent"],
    antonyms: ["modest", "meek"],
  },
  {
    word: "calumny",
    meaning: "slander and defamation",
    partOfSpeech: "Noun",
    examples: [
      "The article was full of calumny against the politician.",
      "He sued the newspaper for spreading calumny about his business.",
    ],
    synonyms: ["slander", "libel", "defamation"],
    antonyms: ["praise", "commendation"],
  },
  {
    word: "candid",
    meaning: "honest; without deception",
    partOfSpeech: "Adjective",
    examples: [
      "I appreciate your candid feedback about my performance.",
      "The CEO gave a candid interview about the company's challenges.",
    ],
    synonyms: ["honest", "frank", "forthright"],
    antonyms: ["deceitful", "dishonest"],
  },
  {
    word: "castigate",
    meaning: "scold someone harshly",
    partOfSpeech: "Verb",
    examples: [
      "The coach castigated the team for their poor performance.",
      "The editorial castigated city officials for their inaction.",
    ],
    synonyms: ["rebuke", "reprimand", "berate"],
    antonyms: ["praise", "commend"],
  },
  {
    word: "caustic",
    meaning: "(of speech) hostile and bitter",
    partOfSpeech: "Adjective",
    examples: [
      "Her caustic remarks created tension in the meeting.",
      "The critic's caustic review devastated the young author.",
    ],
    synonyms: ["biting", "sarcastic", "acerbic"],
    antonyms: ["gentle", "kind"],
  },
  {
    word: "caustic",
    meaning: "(of a chemical) corrosive; acidic",
    partOfSpeech: "Adjective",
    examples: [
      "Wear gloves when handling caustic cleaning solutions.",
      "The spill involved a caustic substance that burned through metal.",
    ],
    synonyms: ["corrosive", "burning", "acidic"],
    antonyms: ["neutral", "mild"],
  },
  {
    word: "construe",
    meaning: "understand something subjectively",
    partOfSpeech: "Verb",
    examples: [
      "Her silence could be construed as agreement.",
      "The law is often construed differently by various judges.",
    ],
    synonyms: ["interpret", "understand", "analyze"],
    antonyms: ["misunderstand", "misinterpret"],
  },
  {
    word: "contrite",
    meaning: "feeling regretful or guilty",
    partOfSpeech: "Adjective",
    examples: [
      "He seemed genuinely contrite about his mistake.",
      "Her contrite apology helped mend their friendship.",
    ],
    synonyms: ["remorseful", "repentant", "apologetic"],
    antonyms: ["unrepentant", "shameless"],
  },
  {
    word: "convoluted",
    meaning: "difficult to understand or follow",
    partOfSpeech: "Adjective",
    examples: [
      "The instructions were so convoluted that no one could follow them.",
      "The movie had a convoluted plot with too many twists.",
    ],
    synonyms: ["complex", "complicated", "intricate"],
    antonyms: ["simple", "clear"],
  },
  {
    word: "covet",
    meaning: "strongly desire; yearn for",
    partOfSpeech: "Verb",
    examples: [
      "She coveted her neighbor's luxurious lifestyle.",
      "Many collectors covet rare first edition books.",
    ],
    synonyms: ["desire", "crave", "yearn"],
    antonyms: ["disdain", "reject"],
  },
  {
    word: "craven",
    meaning: "lacking bravery; weak-kneed",
    partOfSpeech: "Adjective",
    examples: [
      "His craven refusal to stand up for his principles disappointed many.",
      "The craven soldier deserted his post during the attack.",
    ],
    synonyms: ["cowardly", "timid", "fearful"],
    antonyms: ["brave", "courageous"],
  },
  {
    word: "decorum",
    meaning: "politeness and proper behavior",
    partOfSpeech: "Noun",
    examples: [
      "The judge demanded decorum in the courtroom.",
      "She maintained her decorum despite the rude comments.",
    ],
    synonyms: ["propriety", "etiquette", "courtesy"],
    antonyms: ["impropriety", "rudeness"],
  },
  {
    word: "deft",
    meaning: "highly proficient; skilled",
    partOfSpeech: "Adjective",
    examples: [
      "The chef's deft knife skills were impressive.",
      "Her deft handling of the crisis prevented panic.",
    ],
    synonyms: ["skillful", "adept", "nimble"],
    antonyms: ["clumsy", "inept"],
  },
  {
    word: "demur",
    meaning: "hesitate or object; express doubt",
    partOfSpeech: "Verb",
    examples: [
      "She demurred when asked to take on extra responsibilities.",
      "He demurred at the suggestion that he was the best candidate.",
    ],
    synonyms: ["object", "protest", "hesitate"],
    antonyms: ["accept", "agree"],
  },
  {
    word: "demur",
    meaning: "hesitation",
    partOfSpeech: "Noun",
    examples: [
      "After some demur, she finally accepted the award.",
      "There was no demur from the board about the proposed changes.",
    ],
    synonyms: ["objection", "reluctance", "reservation"],
    antonyms: ["approval", "consent"],
  },
  {
    word: "derivative",
    meaning: "based on someone else's work (often used in a negative sense)",
    partOfSpeech: "Adjective",
    examples: [
      "The film felt derivative of earlier, better movies.",
      "Critics dismissed her work as derivative and unoriginal.",
    ],
    synonyms: ["unoriginal", "copied", "imitative"],
    antonyms: ["innovative", "original"],
  },
  {
    word: "desiccate",
    meaning: "dry out; remove all moisture",
    partOfSpeech: "Verb",
    examples: [
      "The desert sun quickly desiccated the plants.",
      "Scientists desiccated the samples for preservation.",
    ],
    synonyms: ["dry", "dehydrate", "parch"],
    antonyms: ["moisten", "rehydrate"],
  },
  {
    word: "diatribe",
    meaning: "an angry rant; verbal abuse",
    partOfSpeech: "Noun",
    examples: [
      "He launched into a diatribe against modern art.",
      "The meeting turned into a diatribe against management.",
    ],
    synonyms: ["tirade", "rant", "harangue"],
    antonyms: ["praise", "commendation"],
  },
  {
    word: "incredulous",
    meaning: "doubtful and disbelieving",
    partOfSpeech: "Adjective",
    examples: [
      "She gave me an incredulous look when I told her the news.",
      "His claims were met with incredulous laughter.",
    ],
    synonyms: ["skeptical", "doubtful", "disbelieving"],
    antonyms: ["believing", "convinced"],
  },
  {
    word: "ingenuous",
    meaning: "naive and lacking experience",
    partOfSpeech: "Adjective",
    examples: [
      "Her ingenuous questions revealed her lack of worldly experience.",
      "The ingenuous young tourist fell for every scam.",
    ],
    synonyms: ["naive", "innocent", "unsuspecting"],
    antonyms: ["worldly", "sophisticated"],
  },
];

export const GROUP_3 = [
  {
    word: "abate",
    meaning: "decrease in intensity; lessen",
    partOfSpeech: "Verb",
    examples: [
      "The storm began to abate by evening.",
      "Medication helped abate her symptoms.",
    ],
    antonyms: ["intensify", "increase"],
    synonyms: ["subside", "diminish"],
  },
  {
    word: "abjure",
    meaning: "strongly reject (an idea); forgo",
    partOfSpeech: "Verb",
    examples: [
      "He abjured his former political beliefs.",
      "The monk abjured all worldly possessions.",
    ],
    antonyms: ["embrace", "accept"],
    synonyms: ["renounce", "repudiate"],
  },
  {
    word: "anomalous",
    meaning: "differing from what is normal; atypical",
    partOfSpeech: "Adjective",
    examples: [
      "The anomalous test results required further investigation.",
      "His cheerful mood was anomalous given the circumstances.",
    ],
    antonyms: ["normal", "typical"],
    synonyms: ["abnormal", "irregular"],
  },
  {
    word: "antipathy",
    meaning: "profound hostility or hatred",
    partOfSpeech: "Noun",
    examples: [
      "She felt deep antipathy toward her rival.",
      "There was mutual antipathy between the two departments.",
    ],
    antonyms: ["affinity", "fondness"],
    synonyms: ["animosity", "aversion"],
  },
  {
    word: "arcane",
    meaning: "comprehended by very few people; secret",
    partOfSpeech: "Adjective",
    examples: [
      "The professor specialized in arcane medieval texts.",
      "The company's decision-making process was arcane to outsiders.",
    ],
    antonyms: ["common", "mainstream"],
    synonyms: ["esoteric", "obscure"],
  },
  {
    word: "arduous",
    meaning: "very challenging; needing great effort",
    partOfSpeech: "Adjective",
    examples: [
      "The hike up the mountain was arduous.",
      "She completed the arduous training program.",
    ],
    antonyms: ["easy", "effortless"],
    synonyms: ["strenuous", "grueling"],
  },
  {
    word: "artless",
    meaning: "naive; inexperienced",
    partOfSpeech: "Adjective",
    examples: [
      "Her artless questions revealed her innocence.",
      "The artless young tourist fell for the scam.",
    ],
    antonyms: ["sophisticated", "worldly"],
    synonyms: ["guileless", "ingenuous"],
  },
  {
    word: "artless",
    meaning: "plain and simple",
    partOfSpeech: "Adjective",
    examples: [
      "The cabin had an artless charm.",
      "He preferred artless designs without ornamentation.",
    ],
    antonyms: ["ornate", "elaborate"],
    synonyms: ["unadorned", "unpretentious"],
  },
  {
    word: "artless",
    meaning: "lacking skill",
    partOfSpeech: "Adjective",
    examples: [
      "The artless painting showed little technique.",
      "His artless attempt at repair made things worse.",
    ],
    antonyms: ["skillful", "accomplished"],
    synonyms: ["amateurish", "clumsy"],
  },
  {
    word: "ascetic",
    meaning: "(of a lifestyle) very strict and lacking luxury",
    partOfSpeech: "Adjective",
    examples: [
      "The monk led an ascetic life of prayer and fasting.",
      "Her ascetic apartment contained only basic necessities.",
    ],
    antonyms: ["indulgent", "luxurious"],
    synonyms: ["austere", "spartan"],
  },
  {
    word: "ascetic",
    meaning: "someone who adopts an ascetic lifestyle",
    partOfSpeech: "Noun",
    examples: [
      "The ascetic lived in a cave for twenty years.",
      "Ancient ascetics often denied themselves physical comforts.",
    ],
    antonyms: ["hedonist", "sybarite"],
    synonyms: ["monk", "austerity"],
  },
  {
    word: "assuage",
    meaning: "decrease a negative feeling",
    partOfSpeech: "Verb",
    examples: [
      "The apology helped assuage her anger.",
      "Nothing could assuage his grief over the loss.",
    ],
    antonyms: ["aggravate", "intensify"],
    synonyms: ["alleviate", "mitigate"],
  },
  {
    word: "assuage",
    meaning: "fulfill a certain desire",
    partOfSpeech: "Verb",
    examples: [
      "The snack assuaged his hunger temporarily.",
      "She read constantly to assuage her thirst for knowledge.",
    ],
    antonyms: ["deprive", "starve"],
    synonyms: ["satisfy", "quench"],
  },
  {
    word: "betray",
    meaning: "unknowingly disclose or reveal",
    partOfSpeech: "Verb",
    examples: [
      "Her trembling hands betrayed her nervousness.",
      "The document betrayed secret government plans.",
    ],
    antonyms: ["conceal", "hide"],
    synonyms: ["reveal", "expose"],
  },
  {
    word: "bucolic",
    meaning: "associated with tranquil rural life",
    partOfSpeech: "Adjective",
    examples: [
      "The painting depicted a bucolic countryside scene.",
      "They longed for a bucolic retreat from city life.",
    ],
    antonyms: ["urban", "metropolitan"],
    synonyms: ["pastoral", "rustic"],
  },
  {
    word: "burgeon",
    meaning: "quickly increase or grow; skyrocket",
    partOfSpeech: "Verb",
    examples: [
      "The tech industry continues to burgeon.",
      "Her interest in art burgeoned after the museum visit.",
    ],
    antonyms: ["decline", "shrink"],
    synonyms: ["flourish", "prosper"],
  },
  {
    word: "cacophonous",
    meaning: "extremely noisy; grating",
    partOfSpeech: "Adjective",
    examples: [
      "The cacophonous construction work made concentration impossible.",
      "The band's early music was deliberately cacophonous.",
    ],
    antonyms: ["harmonious", "melodious"],
    synonyms: ["discordant", "raucous"],
  },
  {
    word: "canonize",
    meaning: "treat like a god; deeply venerate",
    partOfSpeech: "Verb",
    examples: [
      "The church decided to canonize the martyred priest.",
      "Fans tend to canonize their favorite musicians.",
    ],
    antonyms: ["vilify", "denigrate"],
    synonyms: ["deify", "idolize"],
  },
  {
    word: "censure",
    meaning: "strongly criticize or disapprove",
    partOfSpeech: "Verb",
    examples: [
      "The senator was censured for ethical violations.",
      "The editorial censured the mayor's handling of the crisis.",
    ],
    antonyms: ["praise", "commend"],
    synonyms: ["condemn", "reprimand"],
  },
  {
    word: "chicanery",
    meaning: "using deception to attain a certain goal",
    partOfSpeech: "Noun",
    examples: [
      "The election was marred by political chicanery.",
      "He used legal chicanery to avoid paying taxes.",
    ],
    antonyms: ["honesty", "integrity"],
    synonyms: ["trickery", "deceit"],
  },
  {
    word: "coalesce",
    meaning: "bring elements together; unite",
    partOfSpeech: "Verb",
    examples: [
      "The rival factions coalesced to oppose the new law.",
      "Her ideas coalesced into a comprehensive theory.",
    ],
    antonyms: ["disperse", "separate"],
    synonyms: ["merge", "unify"],
  },
  {
    word: "cogent",
    meaning: "persuasive and clear; compelling",
    partOfSpeech: "Adjective",
    examples: [
      "She presented a cogent argument for policy reform.",
      "The lawyer's cogent summary convinced the jury.",
    ],
    antonyms: ["weak", "unconvincing"],
    synonyms: ["logical", "forceful"],
  },
  {
    word: "compelling",
    meaning: "persuasive and clear",
    partOfSpeech: "Adjective",
    examples: [
      "The evidence made a compelling case for conviction.",
      "His compelling testimony changed many minds.",
    ],
    antonyms: ["unpersuasive", "ineffective"],
    synonyms: ["convincing", "cogent"],
  },
  {
    word: "compelling",
    meaning: "attracting interest; fascinating",
    partOfSpeech: "Adjective",
    examples: [
      "The novel had a compelling plot that kept me reading.",
      "She has a compelling personality that draws people in.",
    ],
    antonyms: ["boring", "uninteresting"],
    synonyms: ["captivating", "engrossing"],
  },
  {
    word: "contend",
    meaning: "argue a certain point of view; assert",
    partOfSpeech: "Verb",
    examples: [
      "The author contends that modern art has lost its way.",
      "Scientists contend that climate change is accelerating.",
    ],
    antonyms: ["concede", "agree"],
    synonyms: ["assert", "maintain"],
  },
  {
    word: "contend",
    meaning: "compete",
    partOfSpeech: "Verb",
    examples: [
      "Three teams will contend for the championship.",
      "She contended against more experienced athletes.",
    ],
    antonyms: ["withdraw", "surrender"],
    synonyms: ["vie", "compete"],
  },
  {
    word: "contend",
    meaning: "struggle or attempt to overcome something",
    partOfSpeech: "Verb",
    examples: [
      "The village contended with food shortages after the storm.",
      "He's contending with serious health issues.",
    ],
    antonyms: ["succumb", "yield"],
    synonyms: ["grapple", "cope"],
  },
  {
    word: "copious",
    meaning: "existing in great supply; abundant",
    partOfSpeech: "Adjective",
    examples: [
      "She took copious notes during the lecture.",
      "The region receives copious rainfall in spring.",
    ],
    antonyms: ["scarce", "meager"],
    synonyms: ["plentiful", "ample"],
  },
  {
    word: "cosmopolitan",
    meaning: "(of a city) highly diverse",
    partOfSpeech: "Adjective",
    examples: [
      "New York is a truly cosmopolitan metropolis.",
      "The university attracts a cosmopolitan student body.",
    ],
    antonyms: ["provincial", "homogeneous"],
    synonyms: ["multicultural", "diverse"],
  },
  {
    word: "cosmopolitan",
    meaning: "(of a person) sophisticated and urbane",
    partOfSpeech: "Adjective",
    examples: [
      "His cosmopolitan manners impressed the diplomats.",
      "After years of travel, she had become quite cosmopolitan.",
    ],
    antonyms: ["unsophisticated", "provincial"],
    synonyms: ["worldly", "cultured"],
  },
  {
    word: "deference",
    meaning: "high regard and respect; esteem",
    partOfSpeech: "Noun",
    examples: [
      "The young lawyer treated the judge with deference.",
      "In deference to his age, they let him speak first.",
    ],
    antonyms: ["disrespect", "defiance"],
    synonyms: ["respect", "reverence"],
  },
  {
    word: "desultory",
    meaning: "unplanned; without enthusiasm",
    partOfSpeech: "Adjective",
    examples: [
      "They made desultory attempts to clean the garage.",
      "The meeting proceeded in a desultory fashion.",
    ],
    antonyms: ["enthusiastic", "focused"],
    synonyms: ["halfhearted", "aimless"],
  },
  {
    word: "diffident",
    meaning: "reserved or shy; without confidence",
    partOfSpeech: "Adjective",
    examples: [
      "His diffident manner hid a brilliant mind.",
      "The diffident student rarely spoke in class.",
    ],
    antonyms: ["confident", "assertive"],
    synonyms: ["timid", "bashful"],
  },
  {
    word: "dilatory",
    meaning: "slow and unhurried; meant to stall",
    partOfSpeech: "Adjective",
    examples: [
      "The company used dilatory tactics to avoid payment.",
      "His dilatory response frustrated those waiting for answers.",
    ],
    antonyms: ["prompt", "expeditious"],
    synonyms: ["delaying", "procrastinating"],
  },
  {
    word: "equivocate",
    meaning: "speak evasively; avoid taking a stance",
    partOfSpeech: "Verb",
    examples: [
      "Politicians often equivocate when asked difficult questions.",
      "Don't equivocate - give me a straight answer.",
    ],
    antonyms: ["declare", "affirm"],
    synonyms: ["prevaricate", "hedge"],
  },
  {
    word: "polarize",
    meaning: "separate into two opposing groups",
    partOfSpeech: "Verb",
    examples: [
      "The controversial issue polarized the community.",
      "Social media tends to polarize political opinions.",
    ],
    antonyms: ["unite", "reconcile"],
    synonyms: ["divide", "split"],
  },
  {
    word: "prodigal",
    meaning: "carelessly wasteful; extravagant",
    partOfSpeech: "Adjective",
    examples: [
      "His prodigal spending left him in debt.",
      "The prodigal use of resources couldn't continue.",
    ],
    antonyms: ["frugal", "thrifty"],
    synonyms: ["extravagant", "profligate"],
  },
  {
    word: "prodigal",
    meaning: "a person who is excessively wasteful",
    partOfSpeech: "Noun",
    examples: [
      "The prodigal returned home after wasting his inheritance.",
      "She reformed from being a prodigal to quite frugal.",
    ],
    antonyms: ["miser", "saver"],
    synonyms: ["spendthrift", "wastrel"],
  },
  {
    word: "verbose",
    meaning: "excessively talkative; wordy",
    partOfSpeech: "Adjective",
    examples: [
      "The professor's verbose explanation confused students more.",
      "Legal documents are often unnecessarily verbose.",
    ],
    antonyms: ["concise", "succinct"],
    synonyms: ["loquacious", "prolix"],
  },
];

export const GROUP_4 = [
  {
    word: "abstain",
    meaning: "avoid taking part in something",
    partOfSpeech: "Verb",
    examples: [
      "He decided to abstain from voting in the election.",
      "Doctors advise patients to abstain from alcohol before surgery.",
    ],
    synonyms: ["refrain", "withhold", "desist"],
    antonyms: ["indulge", "partake", "engage"],
  },
  {
    word: "approbation",
    meaning: "appreciation toward someone",
    partOfSpeech: "Noun",
    examples: [
      "The film received widespread approbation from critics.",
      "She smiled with satisfaction at the approbation of her peers.",
    ],
    synonyms: ["approval", "praise", "endorsement"],
    antonyms: ["disapproval", "criticism", "condemnation"],
  },
  {
    word: "cherish",
    meaning: "greatly love or protect something",
    partOfSpeech: "Verb",
    examples: [
      "She will always cherish the memories of her childhood.",
      "They cherish their family traditions deeply.",
    ],
    synonyms: ["treasure", "value", "hold dear"],
    antonyms: ["neglect", "disregard", "despise"],
  },
  {
    word: "corroborate",
    meaning: "lend support to; bolster",
    partOfSpeech: "Verb",
    examples: [
      "The witness could not corroborate the suspect’s alibi.",
      "Studies corroborate the link between stress and heart disease.",
    ],
    synonyms: ["confirm", "verify", "support"],
    antonyms: ["deny", "refute", "contradict"],
  },
  {
    word: "disparate",
    meaning: "different or contrasting",
    partOfSpeech: "Adjective",
    examples: [
      "They came from disparate backgrounds but became close friends.",
      "The novel combines disparate elements of fantasy and science fiction.",
    ],
    synonyms: ["dissimilar", "distinct", "divergent"],
    antonyms: ["similar", "alike", "homogeneous"],
  },
  {
    word: "emulate",
    meaning: "imitate someone or something",
    partOfSpeech: "Verb",
    examples: [
      "She tried to emulate her mentor's dedication to her work.",
      "Young athletes often emulate their sports heroes.",
    ],
    synonyms: ["imitate", "mirror", "copy"],
    antonyms: ["neglect", "ignore", "disregard"],
  },
  {
    word: "enervate",
    meaning: "sap the energy out of someone; fatigue",
    partOfSpeech: "Verb",
    examples: [
      "The long meeting enervated everyone in the room.",
      "A hot climate can enervate even the most energetic people.",
    ],
    synonyms: ["weaken", "exhaust", "debilitate"],
    antonyms: ["invigorate", "energize", "strengthen"],
  },
  {
    word: "ephemeral",
    meaning: "extremely short lasting",
    partOfSpeech: "Adjective",
    examples: [
      "Fame in the digital age is often ephemeral.",
      "The beauty of the sunset was ephemeral but breathtaking.",
    ],
    synonyms: ["fleeting", "transient", "momentary"],
    antonyms: ["enduring", "lasting", "permanent"],
  },
  {
    word: "fervid",
    meaning: "excessively energetic or eager",
    partOfSpeech: "Adjective",
    examples: [
      "The speaker gave a fervid plea for environmental action.",
      "Her fervid imagination brought the story to life.",
    ],
    synonyms: ["passionate", "zealous", "enthusiastic"],
    antonyms: ["apathetic", "indifferent", "unemotional"],
  },
  {
    word: "garrulous",
    meaning: "tending to talk too much; wordy",
    partOfSpeech: "Adjective",
    examples: [
      "The garrulous host kept the conversation going all night.",
      "He grew annoyed with the garrulous old man sitting next to him.",
    ],
    synonyms: ["talkative", "loquacious", "chatty"],
    antonyms: ["taciturn", "reserved", "quiet"],
  },
  {
    word: "incendiary",
    meaning: "provocative; causing conflict",
    partOfSpeech: "Adjective",
    examples: [
      "His incendiary remarks sparked a heated debate.",
      "The article was full of incendiary language meant to provoke outrage.",
    ],
    synonyms: ["provocative", "inflammatory", "agitating"],
    antonyms: ["calming", "soothing", "conciliatory"],
  },
  {
    word: "inimical",
    meaning: "damaging; hostile in manner or tone",
    partOfSpeech: "Adjective",
    examples: [
      "Their relationship became increasingly inimical.",
      "Such policies are inimical to democratic values.",
    ],
    synonyms: ["hostile", "harmful", "adverse"],
    antonyms: ["friendly", "beneficial", "helpful"],
  },
  {
    word: "intimate",
    meaning: "subtly suggest or imply",
    partOfSpeech: "Verb",
    examples: [
      "He intimated that he might retire soon.",
      "Her tone intimated dissatisfaction with the decision.",
    ],
    synonyms: ["suggest", "imply", "hint"],
    antonyms: ["declare", "announce", "proclaim"],
  },
  {
    word: "invigorate",
    meaning: "provide energy or vitality to",
    partOfSpeech: "Verb",
    examples: [
      "A brisk walk in the morning can invigorate you for the day.",
      "The new strategy invigorated the company’s sales team.",
    ],
    synonyms: ["energize", "revitalize", "stimulate"],
    antonyms: ["weaken", "enervate", "exhaust"],
  },
  {
    word: "mitigate",
    meaning: "diminish negative feelings or situation",
    partOfSpeech: "Verb",
    examples: [
      "We need to mitigate the effects of climate change.",
      "The doctor gave her medication to mitigate the pain.",
    ],
    synonyms: ["alleviate", "ease", "lessen"],
    antonyms: ["aggravate", "intensify", "exacerbate"],
  },
  {
    word: "obsolete",
    meaning: "no longer useful; outmoded",
    partOfSpeech: "Adjective",
    examples: [
      "Typewriters have become obsolete in modern offices.",
      "The law is considered obsolete and rarely enforced.",
    ],
    synonyms: ["outdated", "archaic", "antiquated"],
    antonyms: ["modern", "current", "up-to-date"],
  },
  {
    word: "opaque",
    meaning: "unclear; hard to comprehend",
    partOfSpeech: "Adjective",
    examples: [
      "His explanation was too opaque to understand.",
      "The technical jargon made the document opaque to readers.",
    ],
    synonyms: ["obscure", "murky", "confusing"],
    antonyms: ["clear", "transparent", "lucid"],
  },
  {
    word: "opaque",
    meaning: "not able to be seen through",
    partOfSpeech: "Adjective",
    examples: [
      "The windows were opaque with steam.",
      "Frost made the glass completely opaque.",
    ],
    synonyms: ["cloudy", "nontransparent", "frosted"],
    antonyms: ["clear", "transparent", "see-through"],
  },
  {
    word: "paradigmatic",
    meaning: "representing the standard example",
    partOfSpeech: "Adjective",
    examples: [
      "Her career is a paradigmatic example of hard work leading to success.",
      "The novel became a paradigmatic text of modern literature.",
    ],
    synonyms: ["typical", "model", "standard"],
    antonyms: ["atypical", "unusual", "unrepresentative"],
  },
  {
    word: "pedantic",
    meaning: "overly concerned with (minor) details",
    partOfSpeech: "Adjective",
    examples: [
      "His pedantic comments slowed the meeting down.",
      "She has a pedantic habit of correcting everyone’s grammar.",
    ],
    synonyms: ["nitpicky", "fussy", "precise"],
    antonyms: ["careless", "imprecise", "informal"],
  },
  {
    word: "placid",
    meaning: "calm; free from activity or irritation",
    partOfSpeech: "Adjective",
    examples: [
      "The placid lake reflected the sky perfectly.",
      "He remained placid even during the crisis.",
    ],
    synonyms: ["peaceful", "serene", "tranquil"],
    antonyms: ["agitated", "disturbed", "turbulent"],
  },
  {
    word: "polemical",
    meaning: "giving a strong, controversial opinion",
    partOfSpeech: "Adjective",
    examples: [
      "The article was full of polemical criticism of the government.",
      "His polemical stance alienated some of his supporters.",
    ],
    synonyms: ["critical", "contentious", "argumentative"],
    antonyms: ["conciliatory", "diplomatic", "neutral"],
  },
  {
    word: "precipitate",
    meaning: "cause to happen",
    partOfSpeech: "Verb",
    examples: [
      "The incident precipitated a political crisis.",
      "The resignation precipitated the fall of the government.",
    ],
    synonyms: ["trigger", "cause", "spark"],
    antonyms: ["prevent", "halt", "delay"],
  },
  {
    word: "precipitate",
    meaning: "done quickly or suddenly",
    partOfSpeech: "Adjective",
    examples: [
      "His decision was precipitate and poorly thought out.",
      "They made a precipitate withdrawal from the negotiations.",
    ],
    synonyms: ["hasty", "rash", "impulsive"],
    antonyms: ["deliberate", "measured", "cautious"],
  },
  {
    word: "profundity",
    meaning: "great wisdom or intelligence",
    partOfSpeech: "Noun",
    examples: [
      "The profundity of his insights impressed the audience.",
      "Her speech was full of emotional depth and profundity.",
    ],
    synonyms: ["depth", "wisdom", "insight"],
    antonyms: ["shallowness", "superficiality", "ignorance"],
  },
  {
    word: "prophetic",
    meaning: "able to correctly predict the future",
    partOfSpeech: "Adjective",
    examples: [
      "His warnings turned out to be prophetic.",
      "The book’s predictions were eerily prophetic.",
    ],
    synonyms: ["predictive", "visionary", "foretelling"],
    antonyms: ["unpredictive", "mundane", "uninspired"],
  },
  {
    word: "prudent",
    meaning: "wise in decision-making",
    partOfSpeech: "Adjective",
    examples: [
      "It's prudent to save money for emergencies.",
      "She made a prudent investment in real estate.",
    ],
    synonyms: ["wise", "sensible", "cautious"],
    antonyms: ["reckless", "foolish", "imprudent"],
  },
  {
    word: "punctilious",
    meaning: "highly concerned with details or manners",
    partOfSpeech: "Adjective",
    examples: [
      "He was punctilious in observing the rules.",
      "Her punctilious nature made her a great proofreader.",
    ],
    synonyms: ["meticulous", "exact", "scrupulous"],
    antonyms: ["careless", "sloppy", "negligent"],
  },
  {
    word: "recondite",
    meaning: "obscure and difficult to understand",
    partOfSpeech: "Adjective",
    examples: [
      "The professor’s lecture was full of recondite concepts.",
      "His writing is often too recondite for the average reader.",
    ],
    synonyms: ["obscure", "esoteric", "abstruse"],
    antonyms: ["simple", "clear", "accessible"],
  },
  {
    word: "scrupulous",
    meaning: "careful with details",
    partOfSpeech: "Adjective",
    examples: [
      "She kept scrupulous records of every transaction.",
      "The investigation was scrupulous and thorough.",
    ],
    synonyms: ["meticulous", "precise", "thorough"],
    antonyms: ["careless", "negligent", "inaccurate"],
  },
  {
    word: "scrupulous",
    meaning: "possessing moral integrity",
    partOfSpeech: "Adjective",
    examples: [
      "He is known for being scrupulous in all his dealings.",
      "Her scrupulous honesty won everyone's respect.",
    ],
    synonyms: ["honest", "ethical", "principled"],
    antonyms: ["dishonest", "unethical", "corrupt"],
  },
  {
    word: "tranquil",
    meaning: "peaceful; free from activity",
    partOfSpeech: "Adjective",
    examples: [
      "They enjoyed a tranquil afternoon by the lake.",
      "The village is a tranquil place far from the city.",
    ],
    synonyms: ["calm", "serene", "peaceful"],
    antonyms: ["noisy", "chaotic", "agitated"],
  },
  {
    word: "vacillate",
    meaning: "go back and forth with one's view",
    partOfSpeech: "Verb",
    examples: [
      "She vacillated between studying medicine and law.",
      "The government continues to vacillate on the issue.",
    ],
    synonyms: ["waver", "hesitate", "dither"],
    antonyms: ["decide", "choose", "settle"],
  },
];

export const GROUP_5 = [
  {
    word: "aloof",
    meaning: "not warm or friendly; impersonal",
    partOfSpeech: "Adjective",
    examples: [
      "She remained aloof during the group discussion.",
      "His aloof attitude made it hard to approach him.",
    ],
    synonyms: ["distant", "detached", "reserved"],
    antonyms: ["friendly", "sociable"],
  },
  {
    word: "clangor",
    meaning: "a disturbingly loud noise",
    partOfSpeech: "Noun",
    examples: [
      "The clangor of pots and pans echoed through the kitchen.",
      "The clangor from the construction site was unbearable.",
    ],
    synonyms: ["racket", "din", "uproar"],
    antonyms: ["silence", "quiet"],
  },
  {
    word: "conventional",
    meaning: "adhering to established practices or accepted standards",
    partOfSpeech: "Adjective",
    examples: [
      "She wore a conventional dress to the formal event.",
      "He prefers conventional methods over experimental ones.",
    ],
    synonyms: ["traditional", "customary", "standard"],
    antonyms: ["unorthodox", "unconventional"],
  },
  {
    word: "debunk",
    meaning: "prove a belief or idea false",
    partOfSpeech: "Verb",
    examples: [
      "The scientist debunked the myth with evidence.",
      "The article aims to debunk common misconceptions.",
    ],
    synonyms: ["disprove", "expose", "invalidate"],
    antonyms: ["validate", "confirm"],
  },
  {
    word: "diminutive",
    meaning: "exceptionally small in size or stature",
    partOfSpeech: "Adjective",
    examples: [
      "She was a diminutive figure among the tall players.",
      "The diminutive car fit easily into the small space.",
    ],
    synonyms: ["tiny", "petite", "miniature"],
    antonyms: ["huge", "gigantic"],
  },
  {
    word: "discernible",
    meaning: "able to be recognized or understood",
    partOfSpeech: "Adjective",
    examples: [
      "There was a discernible difference in tone.",
      "His accent was barely discernible after years abroad.",
    ],
    synonyms: ["perceptible", "noticeable", "detectable"],
    antonyms: ["indistinct", "imperceptible"],
  },
  {
    word: "enigmatic",
    meaning: "hard to understand; mysterious",
    partOfSpeech: "Adjective",
    examples: [
      "She gave him an enigmatic smile.",
      "The painting has an enigmatic quality.",
    ],
    synonyms: ["mysterious", "puzzling", "cryptic"],
    antonyms: ["clear", "obvious"],
  },
  {
    word: "estranged",
    meaning: "emotionally distanced from someone",
    partOfSpeech: "Adjective",
    examples: [
      "He felt estranged from his old friends.",
      "The argument left them emotionally estranged.",
    ],
    synonyms: ["alienated", "separated", "detached"],
    antonyms: ["connected", "reconciled"],
  },
  {
    word: "extravagant",
    meaning: "excessive, especially in terms of cost",
    partOfSpeech: "Adjective",
    examples: [
      "They threw an extravagant wedding party.",
      "His taste in clothes is rather extravagant.",
    ],
    synonyms: ["lavish", "excessive", "over-the-top"],
    antonyms: ["modest", "frugal"],
  },
  {
    word: "fanciful",
    meaning: "highly imaginative; unrealistic",
    partOfSpeech: "Adjective",
    examples: [
      "The story was too fanciful to be believable.",
      "She had a fanciful idea about traveling through time.",
    ],
    synonyms: ["whimsical", "imaginative", "fantastical"],
    antonyms: ["realistic", "practical"],
  },
  {
    word: "frivolous",
    meaning: "lacking in seriousness or importance; silly",
    partOfSpeech: "Adjective",
    examples: [
      "They wasted money on frivolous purchases.",
      "His frivolous attitude annoyed the serious team.",
      "She's too frivolous to manage such responsibility.",
      "He was seen as frivolous and unreliable.",
    ],
    synonyms: ["silly", "trivial", "petty"],
    antonyms: ["serious", "important"],
  },
  {
    word: "heterogeneous",
    meaning: "composed of varying, diverse elements",
    partOfSpeech: "Adjective",
    examples: [
      "The crowd was a heterogeneous mix of people.",
      "The materials were too heterogeneous to blend well.",
    ],
    synonyms: ["diverse", "varied", "mixed"],
    antonyms: ["homogeneous", "uniform"],
  },
  {
    word: "imperious",
    meaning: "having an arrogant or domineering manner",
    partOfSpeech: "Adjective",
    examples: [
      "His imperious tone silenced the room.",
      "She gave imperious orders that no one dared question.",
    ],
    synonyms: ["overbearing", "authoritative", "commanding"],
    antonyms: ["humble", "meek"],
  },
  {
    word: "impertinent",
    meaning: "disrespectful or inappropriate",
    partOfSpeech: "Adjective",
    examples: [
      "The student was punished for his impertinent remark.",
      "She considered his question impertinent.",
      "The comment was impertinent to the discussion.",
      "He kept making impertinent observations.",
    ],
    synonyms: ["rude", "insolent", "irrelevant"],
    antonyms: ["respectful", "relevant"],
  },
  {
    word: "invasive",
    meaning:
      "infringing on others' privacy / spreading rapidly and causing harm",
    partOfSpeech: "Adjective",
    examples: [
      "She found the reporter’s questions invasive.",
      "Invasive surveillance raised privacy concerns.",
      "The invasive species disrupted the ecosystem.",
      "Invasive plants choked the native vegetation.",
    ],
    synonyms: ["intrusive", "aggressive", "encroaching"],
    antonyms: ["noninvasive", "contained"],
  },
  {
    word: "irresolute",
    meaning: "uncertain or lacking determination",
    partOfSpeech: "Adjective",
    examples: [
      "He stood irresolute at the crossroads.",
      "Her irresolute response disappointed the team.",
    ],
    synonyms: ["indecisive", "vacillating", "hesitant"],
    antonyms: ["resolute", "determined"],
  },
  {
    word: "laudable",
    meaning: "worthy of admiration or praise",
    partOfSpeech: "Adjective",
    examples: [
      "Her efforts to help the homeless are laudable.",
      "He made a laudable attempt to resolve the issue.",
    ],
    synonyms: ["praiseworthy", "commendable", "admirable"],
    antonyms: ["blameworthy", "shameful"],
  },
  {
    word: "lax",
    meaning: "not diligent or careful; casual",
    partOfSpeech: "Adjective",
    examples: [
      "The manager was lax about enforcing deadlines.",
      "Lax security led to the breach.",
    ],
    synonyms: ["careless", "slack", "negligent"],
    antonyms: ["strict", "rigorous"],
  },
  {
    word: "marginalize",
    meaning: "treat someone or something as insignificant",
    partOfSpeech: "Verb",
    examples: [
      "The policies marginalized minority groups.",
      "Artists often feel marginalized by mainstream media.",
    ],
    synonyms: ["exclude", "alienate", "oppress"],
    antonyms: ["include", "empower"],
  },
  {
    word: "panache",
    meaning: "a stylish and confident manner",
    partOfSpeech: "Noun",
    examples: [
      "She delivered the speech with great panache.",
      "He entered the room with flair and panache.",
    ],
    synonyms: ["flair", "style", "elegance"],
    antonyms: ["awkwardness", "clumsiness"],
  },
  {
    word: "plodding",
    meaning: "moving slowly or laboriously",
    partOfSpeech: "Adjective",
    examples: [
      "The movie had a plodding pace.",
      "She took a plodding approach to her tasks.",
    ],
    synonyms: ["slow", "tedious", "labored"],
    antonyms: ["brisk", "energetic"],
  },
  {
    word: "prosaic",
    meaning: "straightforward; unoriginal; unimaginative",
    partOfSpeech: "Adjective",
    examples: [
      "His writing style is prosaic and lacks flair.",
      "The design is functional but prosaic.",
    ],
    synonyms: ["mundane", "dull", "uninspired"],
    antonyms: ["imaginative", "creative"],
  },
  {
    word: "remedial",
    meaning: "serving to correct or cure something",
    partOfSpeech: "Adjective",
    examples: [
      "He was placed in a remedial math class.",
      "The school offers remedial programs for struggling students.",
    ],
    synonyms: ["corrective", "therapeutic", "curative"],
    antonyms: ["harmful", "damaging"],
  },
  {
    word: "restive",
    meaning: "demonstrating difficulty in staying still",
    partOfSpeech: "Adjective",
    examples: [
      "The children became restive during the long ceremony.",
      "The crowd grew restive as the speech dragged on.",
    ],
    synonyms: ["unruly", "fidgety", "restless"],
    antonyms: ["calm", "composed"],
  },
  {
    word: "sporadic",
    meaning: "happening occasionally and irregularly",
    partOfSpeech: "Adjective",
    examples: [
      "There were sporadic power outages throughout the week.",
      "Sporadic rainfall delayed the harvest.",
    ],
    synonyms: ["intermittent", "occasional", "scattered"],
    antonyms: ["frequent", "continuous"],
  },
  {
    word: "stigmatize",
    meaning: "label or mark as disgraceful",
    partOfSpeech: "Verb",
    examples: [
      "Society tends to stigmatize mental illness.",
      "He was unfairly stigmatized by his past mistakes.",
    ],
    synonyms: ["brand", "label", "condemn"],
    antonyms: ["glorify", "praise"],
  },
  {
    word: "undermine",
    meaning: "weaken or sabotage, often subtly",
    partOfSpeech: "Verb",
    examples: [
      "His actions undermined the team's confidence.",
      "The scandal undermined her credibility.",
    ],
    synonyms: ["weaken", "subvert", "erode"],
    antonyms: ["strengthen", "support"],
  },
  {
    word: "weary",
    meaning: "feeling tired or exhausted",
    partOfSpeech: "Adjective",
    examples: [
      "She looked weary after the long journey.",
      "He grew weary of repeating himself.",
    ],
    synonyms: ["tired", "exhausted", "fatigued"],
    antonyms: ["energetic", "rested"],
  },
  {
    word: "zealous",
    meaning: "intensely passionate",
    partOfSpeech: "Adjective",
    examples: [
      "The zealous fans cheered loudly for their team.",
      "She was zealous in advocating for animal rights.",
    ],
    synonyms: ["enthusiastic", "fervent", "passionate"],
    antonyms: ["indifferent", "apathetic"],
  },
];

export const GROUP_6 = [
  {
    word: "admonish",
    meaning: "scold someone seriously",
    partOfSpeech: "Verb",
    synonyms: ["reprimand", "rebuke", "reprove"],
    antonyms: ["praise", "commend"],
    examples: [
      "The teacher admonished the students for cheating on the test.",
      "His mother admonished him for coming home so late.",
    ],
  },
  {
    word: "admonish",
    meaning: "give someone urgent advice",
    partOfSpeech: "Verb",
    synonyms: ["urge", "advise", "exhort"],
    antonyms: ["ignore", "neglect"],
    examples: [
      "The doctor admonished her to quit smoking immediately.",
      "I must admonish you to reconsider this risky investment.",
    ],
  },
  {
    word: "aesthetic",
    meaning: "pertaining to beauty or the appreciation thereof",
    partOfSpeech: "Adjective",
    synonyms: ["artistic", "tasteful", "elegant"],
    antonyms: ["ugly", "unaesthetic"],
    examples: [
      "The museum's aesthetic appeal attracted many visitors.",
      "She made aesthetic improvements to the garden design.",
    ],
  },
  {
    word: "affectation",
    meaning: "a pretense or show meant to impress others",
    partOfSpeech: "Noun",
    synonyms: ["pretension", "pretense", "artificiality"],
    antonyms: ["authenticity", "sincerity"],
    examples: [
      "His British accent was clearly an affectation.",
      "She saw through his affectation of sophistication.",
    ],
  },
  {
    word: "alleviate",
    meaning: "lessen the intensity or severity of something negative",
    partOfSpeech: "Verb",
    synonyms: ["ease", "relieve", "mitigate"],
    antonyms: ["exacerbate", "aggravate"],
    examples: [
      "The medication helped alleviate her chronic pain.",
      "Volunteers worked to alleviate suffering after the disaster.",
    ],
  },
  {
    word: "analogous",
    meaning: "comparable or similar to",
    partOfSpeech: "Adjective",
    synonyms: ["comparable", "similar", "parallel"],
    antonyms: ["dissimilar", "unlike"],
    examples: [
      "The structure of an atom is analogous to a solar system.",
      "Their relationship was analogous to that of siblings.",
    ],
  },
  {
    word: "bolster",
    meaning: "lend support or boost",
    partOfSpeech: "Verb",
    synonyms: ["support", "strengthen", "reinforce"],
    antonyms: ["weaken", "undermine"],
    examples: [
      "The new evidence bolstered their case in court.",
      "She drank coffee to bolster her energy before the meeting.",
    ],
  },
  {
    word: "chauvinistic",
    meaning: "excessively patriotic or biased in favor of a group or cause",
    partOfSpeech: "Adjective",
    synonyms: ["jingoistic", "patriotic", "biased"],
    antonyms: ["impartial", "open-minded"],
    examples: [
      "His chauvinistic remarks about other countries offended many.",
      "The company was criticized for its chauvinistic hiring practices.",
    ],
  },
  {
    word: "connoisseur",
    meaning: "a discerning expert in matters of taste",
    partOfSpeech: "Noun",
    synonyms: ["expert", "specialist", "aficionado"],
    antonyms: ["amateur", "novice"],
    examples: [
      "As a wine connoisseur, he could identify rare vintages.",
      "The art connoisseur recognized the forgery immediately.",
    ],
  },
  {
    word: "dissemble",
    meaning: "hide or misrepresent one's true feelings or beliefs",
    partOfSpeech: "Verb",
    synonyms: ["pretend", "feign", "conceal"],
    antonyms: ["reveal", "disclose"],
    examples: [
      "He dissembled his disappointment with a forced smile.",
      "Politicians often dissemble when answering difficult questions.",
    ],
  },
  {
    word: "dogged",
    meaning: "demonstrating tenacity and an unwillingness to give up",
    partOfSpeech: "Adjective",
    synonyms: ["tenacious", "persistent", "determined"],
    antonyms: ["yielding", "lazy"],
    examples: [
      "Her dogged determination led to the discovery.",
      "The detective pursued the case with dogged persistence.",
    ],
  },
  {
    word: "dupe",
    meaning: "trick or fool someone",
    partOfSpeech: "Verb",
    synonyms: ["deceive", "trick", "mislead"],
    antonyms: ["enlighten", "inform"],
    examples: [
      "Scammers duped elderly victims out of their savings.",
      "He felt duped after realizing the product didn't work as advertised.",
    ],
  },
  {
    word: "empirical",
    meaning: "based on observation or experience rather than conjecture",
    partOfSpeech: "Adjective",
    synonyms: ["observational", "practical", "factual"],
    antonyms: ["theoretical", "speculative"],
    examples: [
      "Scientists rely on empirical evidence to support theories.",
      "The study provided empirical data about consumer behavior.",
    ],
  },
  {
    word: "engender",
    meaning: "produce or stimulate the development of something",
    partOfSpeech: "Verb",
    synonyms: ["cause", "generate", "provoke"],
    antonyms: ["prevent", "halt"],
    examples: [
      "The controversial policy engendered much debate.",
      "His kindness engendered trust among his colleagues.",
    ],
  },
  {
    word: "entitled",
    meaning: "assuming oneself to be deserving of special rights or privileges",
    partOfSpeech: "Adjective",
    synonyms: ["privileged", "self-important", "presumptuous"],
    antonyms: ["humble", "modest"],
    examples: [
      "The entitled customer demanded special treatment.",
      "His entitled attitude made him unpopular with coworkers.",
    ],
  },
  {
    word: "pertinacious",
    meaning: "stubbornly holding onto a belief or course of action",
    partOfSpeech: "Adjective",
    synonyms: ["persistent", "obstinate", "resolute"],
    antonyms: ["compliant", "yielding"],
    examples: [
      "Her pertinacious refusal to compromise stalled negotiations.",
      "The pertinacious reporter kept investigating despite obstacles.",
    ],
  },
  {
    word: "presumptuous",
    meaning: "overstepping boundaries, often in an overconfident way",
    partOfSpeech: "Adjective",
    synonyms: ["brazen", "forward", "arrogant"],
    antonyms: ["modest", "deferential"],
    examples: [
      "It was presumptuous of him to speak for the entire group.",
      "Her presumptuous suggestion offended the senior staff.",
    ],
  },
  {
    word: "probity",
    meaning: "the characteristic of having strong ethical standards",
    partOfSpeech: "Noun",
    synonyms: ["integrity", "honesty", "uprightness"],
    antonyms: ["corruption", "dishonesty"],
    examples: [
      "The judge was respected for his unquestionable probity.",
      "Financial advisors must demonstrate absolute probity.",
    ],
  },
  {
    word: "proliferate",
    meaning: "rapidly increase or multiply in number",
    partOfSpeech: "Verb",
    synonyms: ["multiply", "spread", "expand"],
    antonyms: ["diminish", "decrease"],
    examples: [
      "Fast food chains continue to proliferate worldwide.",
      "Online scams proliferated during the pandemic.",
    ],
  },
  {
    word: "specious",
    meaning: "seemingly reasonable but actually wrong",
    partOfSpeech: "Adjective",
    synonyms: ["misleading", "fallacious", "deceptive"],
    antonyms: ["valid", "genuine"],
    examples: [
      "His specious argument fell apart under scrutiny.",
      "The advertisement made specious claims about the product.",
    ],
  },
  {
    word: "spurious",
    meaning: "not genuine; bogus",
    partOfSpeech: "Adjective",
    synonyms: ["false", "phony", "fraudulent"],
    antonyms: ["authentic", "genuine"],
    examples: [
      "The museum discovered the painting was a spurious imitation.",
      "He made spurious accusations without evidence.",
    ],
  },
  {
    word: "subjective",
    meaning: "pertaining to personal feelings rather than objective reality",
    partOfSpeech: "Adjective",
    synonyms: ["personal", "emotional", "biased"],
    antonyms: ["objective", "neutral"],
    examples: [
      "Art appreciation is largely subjective.",
      "Her review contained many subjective opinions.",
    ],
  },
  {
    word: "subvert",
    meaning: "undermine or weaken, typically an authority of some sort",
    partOfSpeech: "Verb",
    synonyms: ["undermine", "destabilize", "sabotage"],
    antonyms: ["support", "uphold"],
    examples: [
      "The rebels sought to subvert the government.",
      "The parody subtly subverted traditional gender roles.",
    ],
  },
  {
    word: "timorous",
    meaning: "displaying nervousness; lacking confidence",
    partOfSpeech: "Adjective",
    synonyms: ["shy", "timid", "hesitant"],
    antonyms: ["bold", "confident"],
    examples: [
      "The timorous intern hesitated to share her ideas.",
      "His timorous approach to negotiations weakened his position.",
    ],
  },
  {
    word: "tortuous",
    meaning: "marked by numerous twists or turns",
    partOfSpeech: "Adjective",
    synonyms: ["winding", "twisting", "meandering"],
    antonyms: ["straight", "direct"],
    examples: [
      "The tortuous mountain road made driving difficult.",
      "They followed the tortuous path through the dense forest.",
    ],
  },
  {
    word: "tortuous",
    meaning: "overly complicated and long",
    partOfSpeech: "Adjective",
    synonyms: ["convoluted", "complex", "lengthy"],
    antonyms: ["simple", "clear"],
    examples: [
      "The contract's tortuous language confused many signers.",
      "The approval process became tortuous with added regulations.",
    ],
  },
  {
    word: "tractable",
    meaning: "easily managed or controlled",
    partOfSpeech: "Adjective",
    synonyms: ["manageable", "docile", "obedient"],
    antonyms: ["unruly", "stubborn"],
    examples: [
      "The tractable horse was perfect for beginner riders.",
      "She found the students remarkably tractable after lunch.",
    ],
  },
  {
    word: "tractable",
    meaning: "(of a situation) easy to solve or handle",
    partOfSpeech: "Adjective",
    synonyms: ["solvable", "resolvable", "workable"],
    antonyms: ["complicated", "intractable"],
    examples: [
      "The math problem proved surprisingly tractable.",
      "What seemed like a crisis became tractable with proper analysis.",
    ],
  },
  {
    word: "transient",
    meaning: "not lasting, enduring, or permanent; transitory",
    partOfSpeech: "Adjective",
    synonyms: ["temporary", "fleeting", "short-lived"],
    antonyms: ["permanent", "enduring"],
    examples: [
      "The drug's effects were powerful but transient.",
      "They enjoyed the transient beauty of the cherry blossoms.",
    ],
  },
  {
    word: "ubiquitous",
    meaning: "being everywhere at once",
    partOfSpeech: "Adjective",
    synonyms: ["omnipresent", "universal", "pervasive"],
    antonyms: ["rare", "scarce"],
    examples: [
      "Smartphones have become ubiquitous in modern society.",
      "The ubiquitous advertising made the product instantly recognizable.",
    ],
  },
  {
    word: "underscore",
    meaning: "emphasize or show the importance of something",
    partOfSpeech: "Verb",
    synonyms: ["emphasize", "highlight", "stress"],
    antonyms: ["downplay", "minimize"],
    examples: [
      "The report underscores the need for immediate action.",
      "Her speech underscored the values of equality and justice.",
    ],
  },
  {
    word: "venal",
    meaning: "open to bribery or corruption",
    partOfSpeech: "Adjective",
    synonyms: ["corrupt", "dishonest", "bribable"],
    antonyms: ["honest", "incorruptible"],
    examples: [
      "The venal official accepted bribes for political favors.",
      "The investigation revealed a venal system of kickbacks.",
    ],
  },
  {
    word: "venerate",
    meaning: "regard with deep respect or reverence",
    partOfSpeech: "Verb",
    synonyms: ["revere", "respect", "honor"],
    antonyms: ["disrespect", "dishonor"],
    examples: [
      "Many cultures venerate their ancestors.",
      "The scientist was venerated for her groundbreaking discoveries.",
    ],
  },
];

// Export all groups in an object for easy access
export const ALL_GROUPS = {
  "Group 1": GROUP_1,
  "Group 2": GROUP_2,
  "Group 3": GROUP_3,
  "Group 4": GROUP_4,
  "Group 5": GROUP_5,
  "Group 6": GROUP_6,
};
