export const GROUP_1 = [
  {
    word: "abound",
    meaning: "be present in large quantities",
    partOfSpeech: "Verb",
    exampleUse1: "Wildlife abounds in this untouched forest.",
    exampleUse2: "Opportunities abound for skilled workers in this industry.",
  },
  {
    word: "amorphous",
    meaning: "lacking structure; unclear",
    partOfSpeech: "Adjective",
    exampleUse1: "The amorphous cloud of gas slowly took shape.",
    exampleUse2:
      "Her amorphous career path made it hard to define her expertise.",
  },
  {
    word: "austere",
    meaning: "(of a person) strict and stern in character",
    partOfSpeech: "Adjective",
    exampleUse1: "The austere teacher tolerated no nonsense in her classroom.",
    exampleUse2: "His austere demeanor made him seem unapproachable.",
  },
  {
    word: "austere",
    meaning: "(of living conditions) lacking luxury; extremely harsh",
    partOfSpeech: "Adjective",
    exampleUse1:
      "The monks lived in austere conditions with minimal possessions.",
    exampleUse2:
      "The prison cell was austere, containing only a cot and toilet.",
  },
  {
    word: "belie",
    meaning: "give a false impression of; mask",
    partOfSpeech: "Verb",
    exampleUse1: "His calm voice belied the anger he felt inside.",
    exampleUse2: "The cheerful decor belied the building's troubled history.",
  },
  {
    word: "capricious",
    meaning: "having varying moods; fickle",
    partOfSpeech: "Adjective",
    exampleUse1:
      "The capricious weather changed from sunny to stormy in minutes.",
    exampleUse2: "Dealing with a capricious boss required constant adaptation.",
  },
  {
    word: "cerebral",
    meaning: "related to the brain",
    partOfSpeech: "Adjective",
    exampleUse1:
      "The cerebral hemorrhage required immediate medical attention.",
    exampleUse2: "Doctors studied the cerebral activity during the experiment.",
  },
  {
    word: "cerebral",
    meaning: "intellectual; focused on learning rather than emotion",
    partOfSpeech: "Adjective",
    exampleUse1: "She preferred cerebral puzzles over physical challenges.",
    exampleUse2: "The film was too cerebral for mainstream audiences.",
  },
  {
    word: "congenial",
    meaning:
      "(of a person) likable and friendly, often due to shared interests",
    partOfSpeech: "Adjective",
    exampleUse1: "We found our new neighbors to be quite congenial.",
    exampleUse2: "The congenial professor made learning enjoyable.",
  },
  {
    word: "congenial",
    meaning: "(of a thing) enjoyable because it aligns with one's tendencies",
    partOfSpeech: "Adjective",
    exampleUse1: "The quiet café provided a congenial atmosphere for writing.",
    exampleUse2: "He found the company's values congenial to his own.",
  },
  {
    word: "conspicuous",
    meaning: "easily noticed; obvious",
    partOfSpeech: "Adjective",
    exampleUse1: "Her bright red coat made her conspicuous in the crowd.",
    exampleUse2: "There was a conspicuous absence of managers at the meeting.",
  },
  {
    word: "cursory",
    meaning: "lacking effort; without care",
    partOfSpeech: "Adjective",
    exampleUse1: "He gave the report only a cursory glance before signing.",
    exampleUse2: "The cursory inspection missed several safety violations.",
  },
  {
    word: "daunting",
    meaning: "scary or frightening; (of a task) seeming impossible",
    partOfSpeech: "Adjective",
    exampleUse1: "The sheer size of the project was daunting.",
    exampleUse2: "Facing the champion boxer seemed a daunting prospect.",
  },
  {
    word: "deify",
    meaning: "look up to someone or something as a god",
    partOfSpeech: "Verb",
    exampleUse1: "Some fans deify their favorite celebrities.",
    exampleUse2: "Ancient cultures would often deify natural phenomena.",
  },
  {
    word: "didactic",
    meaning:
      "meant for teaching; educational, sometimes in a condescending manner",
    partOfSpeech: "Adjective",
    exampleUse1: "The fable had a clear didactic purpose about honesty.",
    exampleUse2: "Her didactic tone made the students feel patronized.",
  },
  {
    word: "disseminate",
    meaning: "distribute or circulate broadly",
    partOfSpeech: "Verb",
    exampleUse1: "The organization works to disseminate health information.",
    exampleUse2: "Social media helps disseminate news quickly.",
  },
  {
    word: "feasible",
    meaning: "likely to be achieved; practical",
    partOfSpeech: "Adjective",
    exampleUse1: "The construction plan seems feasible within our budget.",
    exampleUse2: "Is it feasible to complete this project by Friday?",
  },
  {
    word: "flout",
    meaning: "break a rule without guilt",
    partOfSpeech: "Verb",
    exampleUse1: "The company continued to flout environmental regulations.",
    exampleUse2: "He openly flouted the dress code by wearing jeans.",
  },
  {
    word: "homogeneous",
    meaning: "composed of similar parts; alike",
    partOfSpeech: "Adjective",
    exampleUse1:
      "The neighborhood was homogeneous, with nearly identical houses.",
    exampleUse2: "The team lacked diversity, being homogeneous in background.",
  },
  {
    word: "humdrum",
    meaning: "boring; unlikely to excite",
    partOfSpeech: "Adjective",
    exampleUse1: "She longed to escape her humdrum routine.",
    exampleUse2: "The meeting was a humdrum affair with little discussion.",
  },
  {
    word: "insipid",
    meaning: "without flavor; lacking energy",
    partOfSpeech: "Adjective",
    exampleUse1: "The soup was insipid and needed more seasoning.",
    exampleUse2: "His insipid presentation failed to engage the audience.",
  },
  {
    word: "loquacious",
    meaning: "likely to talk a lot; wordy",
    partOfSpeech: "Adjective",
    exampleUse1: "The loquacious tour guide shared endless stories.",
    exampleUse2: "Her loquacious nature made her perfect for radio.",
  },
  {
    word: "misanthropic",
    meaning: "having a distaste for humans and society",
    partOfSpeech: "Adjective",
    exampleUse1: "The misanthropic old man refused all visitors.",
    exampleUse2: "His misanthropic views made him avoid crowded places.",
  },
  {
    word: "misnomer",
    meaning: "a misleading or inaccurate name",
    partOfSpeech: "Noun",
    exampleUse1:
      "'Fun Size' candy bars are a misnomer for such small portions.",
    exampleUse2:
      "The 'common cold' is a misnomer since there are many viruses.",
  },
  {
    word: "negligent",
    meaning: "lacking care or attention",
    partOfSpeech: "Adjective",
    exampleUse1: "The negligent driver caused the accident.",
    exampleUse2: "The landlord was negligent in maintaining the property.",
  },
  {
    word: "obsequious",
    meaning: "excessively submissive to authority",
    partOfSpeech: "Adjective",
    exampleUse1:
      "The obsequious assistant agreed with everything the boss said.",
    exampleUse2: "His obsequious behavior made his colleagues uncomfortable.",
  },
  {
    word: "placate",
    meaning: "decrease someone's anger or other negative emotion",
    partOfSpeech: "Verb",
    exampleUse1: "The manager tried to placate the angry customer.",
    exampleUse2: "They offered concessions to placate the protesters.",
  },
  {
    word: "proclivity",
    meaning: "a fondness or liking for something",
    partOfSpeech: "Noun",
    exampleUse1: "She had a proclivity for spicy foods.",
    exampleUse2:
      "His early proclivity for music led to a career in composition.",
  },
  {
    word: "puerile",
    meaning: "immature and childish",
    partOfSpeech: "Adjective",
    exampleUse1: "The puerile jokes were inappropriate for the meeting.",
    exampleUse2: "His puerile behavior embarrassed his colleagues.",
  },
  {
    word: "quixotic",
    meaning: "excessively visionary; unfeasible",
    partOfSpeech: "Adjective",
    exampleUse1: "His quixotic plan to end world hunger was unrealistic.",
    exampleUse2: "The quixotic quest for perfection wasted valuable time.",
  },
  {
    word: "spendthrift",
    meaning: "someone who spends money recklessly",
    partOfSpeech: "Noun",
    exampleUse1: "The spendthrift heir quickly wasted his inheritance.",
    exampleUse2: "Her spendthrift habits left her constantly in debt.",
  },
  {
    word: "taciturn",
    meaning: "of few words; speaking little",
    partOfSpeech: "Adjective",
    exampleUse1: "The taciturn cowboy rarely joined conversations.",
    exampleUse2: "His taciturn nature made him seem mysterious.",
  },
  {
    word: "wary",
    meaning: "exercising caution; careful",
    partOfSpeech: "Adjective",
    exampleUse1: "Investors were wary of putting money into the new venture.",
    exampleUse2: "She grew wary of strangers after the incident.",
  },
];

export const GROUP_2 = [
  {
    word: "adulterate",
    meaning: "damage the quality of; corrupt",
    partOfSpeech: "Verb",
    exampleUse1:
      "The company was fined for adulterating their products with cheap fillers.",
    exampleUse2: "Adding water to milk adulterates its nutritional value.",
  },
  {
    word: "advocate",
    meaning: "support; be in favor of",
    partOfSpeech: "Verb",
    exampleUse1: "She advocates for better healthcare policies.",
    exampleUse2: "The professor advocates using primary sources in research.",
  },
  {
    word: "advocate",
    meaning: "someone who supports a cause, organization, or person",
    partOfSpeech: "Noun",
    exampleUse1: "He works as a child advocate in family court.",
    exampleUse2:
      "The environmental advocate spoke passionately about conservation.",
  },
  {
    word: "aggrandize",
    meaning: "enhance one's power or standing",
    partOfSpeech: "Verb",
    exampleUse1:
      "The dictator sought to aggrandize himself through propaganda.",
    exampleUse2:
      "She aggrandized her reputation by taking credit for others' work.",
  },
  {
    word: "alacrity",
    meaning: "eagerness to do something",
    partOfSpeech: "Noun",
    exampleUse1: "She accepted the challenge with alacrity.",
    exampleUse2:
      "The staff responded with alacrity to the emergency situation.",
  },
  {
    word: "ambivalent",
    meaning: "having conflicting emotions; unsure",
    partOfSpeech: "Adjective",
    exampleUse1:
      "I feel ambivalent about the job offer - it pays well but requires relocation.",
    exampleUse2: "His ambivalent attitude made decision-making difficult.",
  },
  {
    word: "ameliorate",
    meaning: "improve a bad feeling or bad situation",
    partOfSpeech: "Verb",
    exampleUse1: "The new policy ameliorated working conditions.",
    exampleUse2: "Medication helped ameliorate her chronic pain.",
  },
  {
    word: "amenable",
    meaning: "(of a person) receptive to change; open",
    partOfSpeech: "Adjective",
    exampleUse1: "The team was amenable to trying the new strategy.",
    exampleUse2: "She's generally amenable to constructive criticism.",
  },
  {
    word: "amenable",
    meaning: "(of a thing) responsive to",
    partOfSpeech: "Adjective",
    exampleUse1: "This material is amenable to various shaping techniques.",
    exampleUse2: "The disease is amenable to treatment with antibiotics.",
  },
  {
    word: "anachronistic",
    meaning: "of the wrong time or era",
    partOfSpeech: "Adjective",
    exampleUse1:
      "The film's depiction of smartphones in the 1920s was anachronistic.",
    exampleUse2:
      "His views on gender roles seem anachronistic in modern society.",
  },
  {
    word: "audacious",
    meaning: "bold; unafraid of risks",
    partOfSpeech: "Adjective",
    exampleUse1: "Her audacious plan to climb the mountain alone succeeded.",
    exampleUse2: "The startup made an audacious bid for the contract.",
  },
  {
    word: "audacious",
    meaning: "rude; exhibiting disrespect",
    partOfSpeech: "Adjective",
    exampleUse1: "His audacious remarks offended many attendees.",
    exampleUse2: "The student's audacious behavior disrupted the class.",
  },
  {
    word: "avaricious",
    meaning: "greedy; always wanting more",
    partOfSpeech: "Adjective",
    exampleUse1:
      "The avaricious CEO prioritized profits over employee welfare.",
    exampleUse2:
      "His avaricious nature made him an unpopular business partner.",
  },
  {
    word: "banal",
    meaning: "unoriginal and dull; lacking creativity",
    partOfSpeech: "Adjective",
    exampleUse1: "The speech was full of banal platitudes.",
    exampleUse2: "The movie's plot was banal and predictable.",
  },
  {
    word: "benign",
    meaning: "harmless; having little effect",
    partOfSpeech: "Adjective",
    exampleUse1: "The tumor turned out to be benign.",
    exampleUse2: "The new law had a benign impact on small businesses.",
  },
  {
    word: "benign",
    meaning: "(of a person's character) kind hearted; nice",
    partOfSpeech: "Adjective",
    exampleUse1: "His benign smile put everyone at ease.",
    exampleUse2: "The teacher had a benign approach to discipline.",
  },
  {
    word: "brazen",
    meaning: "shameless and excessively forward",
    partOfSpeech: "Adjective",
    exampleUse1: "She made a brazen attempt to cut in line.",
    exampleUse2: "The brazen theft occurred in broad daylight.",
  },
  {
    word: "calumny",
    meaning: "slander and defamation",
    partOfSpeech: "Noun",
    exampleUse1: "The article was full of calumny against the politician.",
    exampleUse2:
      "He sued the newspaper for spreading calumny about his business.",
  },
  {
    word: "candid",
    meaning: "honest; without deception",
    partOfSpeech: "Adjective",
    exampleUse1: "I appreciate your candid feedback about my performance.",
    exampleUse2:
      "The CEO gave a candid interview about the company's challenges.",
  },
  {
    word: "castigate",
    meaning: "scold someone harshly",
    partOfSpeech: "Verb",
    exampleUse1: "The coach castigated the team for their poor performance.",
    exampleUse2: "The editorial castigated city officials for their inaction.",
  },
  {
    word: "caustic",
    meaning: "(of speech) hostile and bitter",
    partOfSpeech: "Adjective",
    exampleUse1: "Her caustic remarks created tension in the meeting.",
    exampleUse2: "The critic's caustic review devastated the young author.",
  },
  {
    word: "caustic",
    meaning: "(of a chemical) corrosive; acidic",
    partOfSpeech: "Adjective",
    exampleUse1: "Wear gloves when handling caustic cleaning solutions.",
    exampleUse2:
      "The spill involved a caustic substance that burned through metal.",
  },
  {
    word: "construe",
    meaning: "understand something subjectively",
    partOfSpeech: "Verb",
    exampleUse1: "Her silence could be construed as agreement.",
    exampleUse2: "The law is often construed differently by various judges.",
  },
  {
    word: "contrite",
    meaning: "feeling regretful or guilty",
    partOfSpeech: "Adjective",
    exampleUse1: "He seemed genuinely contrite about his mistake.",
    exampleUse2: "Her contrite apology helped mend their friendship.",
  },
  {
    word: "convoluted",
    meaning: "difficult to understand or follow",
    partOfSpeech: "Adjective",
    exampleUse1:
      "The instructions were so convoluted that no one could follow them.",
    exampleUse2: "The movie had a convoluted plot with too many twists.",
  },
  {
    word: "covet",
    meaning: "strongly desire; yearn for",
    partOfSpeech: "Verb",
    exampleUse1: "She coveted her neighbor's luxurious lifestyle.",
    exampleUse2: "Many collectors covet rare first edition books.",
  },
  {
    word: "craven",
    meaning: "lacking bravery; weak-kneed",
    partOfSpeech: "Adjective",
    exampleUse1:
      "His craven refusal to stand up for his principles disappointed many.",
    exampleUse2: "The craven soldier deserted his post during the attack.",
  },
  {
    word: "decorum",
    meaning: "politeness and proper behavior",
    partOfSpeech: "Noun",
    exampleUse1: "The judge demanded decorum in the courtroom.",
    exampleUse2: "She maintained her decorum despite the rude comments.",
  },
  {
    word: "deft",
    meaning: "highly proficient; skilled",
    partOfSpeech: "Adjective",
    exampleUse1: "The chef's deft knife skills were impressive.",
    exampleUse2: "Her deft handling of the crisis prevented panic.",
  },
  {
    word: "demur",
    meaning: "hesitate or object; express doubt",
    partOfSpeech: "Verb",
    exampleUse1: "She demurred when asked to take on extra responsibilities.",
    exampleUse2:
      "He demurred at the suggestion that he was the best candidate.",
  },
  {
    word: "demur",
    meaning: "hesitation",
    partOfSpeech: "Noun",
    exampleUse1: "After some demur, she finally accepted the award.",
    exampleUse2:
      "There was no demur from the board about the proposed changes.",
  },
  {
    word: "derivative",
    meaning: "based on someone else's work (often used in a negative sense)",
    partOfSpeech: "Adjective",
    exampleUse1: "The film felt derivative of earlier, better movies.",
    exampleUse2: "Critics dismissed her work as derivative and unoriginal.",
  },
  {
    word: "desiccate",
    meaning: "dry out; remove all moisture",
    partOfSpeech: "Verb",
    exampleUse1: "The desert sun quickly desiccated the plants.",
    exampleUse2: "Scientists desiccated the samples for preservation.",
  },
  {
    word: "diatribe",
    meaning: "an angry rant; verbal abuse",
    partOfSpeech: "Noun",
    exampleUse1: "He launched into a diatribe against modern art.",
    exampleUse2: "The meeting turned into a diatribe against management.",
  },
  {
    word: "incredulous",
    meaning: "doubtful and disbelieving",
    partOfSpeech: "Adjective",
    exampleUse1: "She gave me an incredulous look when I told her the news.",
    exampleUse2: "His claims were met with incredulous laughter.",
  },
  {
    word: "ingenuous",
    meaning: "naive and lacking experience",
    partOfSpeech: "Adjective",
    exampleUse1:
      "Her ingenuous questions revealed her lack of worldly experience.",
    exampleUse2: "The ingenuous young tourist fell for every scam.",
  },
];

export const GROUP_3 = [
  {
    word: "abate",
    meaning: "decrease in intensity; lessen",
    partOfSpeech: "Verb",
    exampleUse1: "The storm began to abate by evening.",
    exampleUse2: "Medication helped abate her symptoms.",
  },
  {
    word: "abjure",
    meaning: "strongly reject (an idea); forgo",
    partOfSpeech: "Verb",
    exampleUse1: "He abjured his former political beliefs.",
    exampleUse2: "The monk abjured all worldly possessions.",
  },
  {
    word: "anomalous",
    meaning: "differing from what is normal; atypical",
    partOfSpeech: "Adjective",
    exampleUse1: "The anomalous test results required further investigation.",
    exampleUse2: "His cheerful mood was anomalous given the circumstances.",
  },
  {
    word: "antipathy",
    meaning: "profound hostility or hatred",
    partOfSpeech: "Noun",
    exampleUse1: "She felt deep antipathy toward her rival.",
    exampleUse2: "There was mutual antipathy between the two departments.",
  },
  {
    word: "arcane",
    meaning: "comprehended by very few people; secret",
    partOfSpeech: "Adjective",
    exampleUse1: "The professor specialized in arcane medieval texts.",
    exampleUse2:
      "The company's decision-making process was arcane to outsiders.",
  },
  {
    word: "arduous",
    meaning: "very challenging; needing great effort",
    partOfSpeech: "Adjective",
    exampleUse1: "The hike up the mountain was arduous.",
    exampleUse2: "She completed the arduous training program.",
  },
  {
    word: "artless",
    meaning: "naive; inexperienced",
    partOfSpeech: "Adjective",
    exampleUse1: "Her artless questions revealed her innocence.",
    exampleUse2: "The artless young tourist fell for the scam.",
  },
  {
    word: "artless",
    meaning: "plain and simple",
    partOfSpeech: "Adjective",
    exampleUse1: "The cabin had an artless charm.",
    exampleUse2: "He preferred artless designs without ornamentation.",
  },
  {
    word: "artless",
    meaning: "lacking skill",
    partOfSpeech: "Adjective",
    exampleUse1: "The artless painting showed little technique.",
    exampleUse2: "His artless attempt at repair made things worse.",
  },
  {
    word: "ascetic",
    meaning: "(of a lifestyle) very strict and lacking luxury",
    partOfSpeech: "Adjective",
    exampleUse1: "The monk led an ascetic life of prayer and fasting.",
    exampleUse2: "Her ascetic apartment contained only basic necessities.",
  },
  {
    word: "ascetic",
    meaning: "someone who adopts an ascetic lifestyle",
    partOfSpeech: "Noun",
    exampleUse1: "The ascetic lived in a cave for twenty years.",
    exampleUse2: "Ancient ascetics often denied themselves physical comforts.",
  },
  {
    word: "assuage",
    meaning: "decrease a negative feeling",
    partOfSpeech: "Verb",
    exampleUse1: "The apology helped assuage her anger.",
    exampleUse2: "Nothing could assuage his grief over the loss.",
  },
  {
    word: "assuage",
    meaning: "fulfill a certain desire",
    partOfSpeech: "Verb",
    exampleUse1: "The snack assuaged his hunger temporarily.",
    exampleUse2: "She read constantly to assuage her thirst for knowledge.",
  },
  {
    word: "betray",
    meaning: "unknowingly disclose or reveal",
    partOfSpeech: "Verb",
    exampleUse1: "Her trembling hands betrayed her nervousness.",
    exampleUse2: "The document betrayed secret government plans.",
  },
  {
    word: "bucolic",
    meaning: "associated with tranquil rural life",
    partOfSpeech: "Adjective",
    exampleUse1: "The painting depicted a bucolic countryside scene.",
    exampleUse2: "They longed for a bucolic retreat from city life.",
  },
  {
    word: "burgeon",
    meaning: "quickly increase or grow; skyrocket",
    partOfSpeech: "Verb",
    exampleUse1: "The tech industry continues to burgeon.",
    exampleUse2: "Her interest in art burgeoned after the museum visit.",
  },
  {
    word: "cacophonous",
    meaning: "extremely noisy; grating",
    partOfSpeech: "Adjective",
    exampleUse1:
      "The cacophonous construction work made concentration impossible.",
    exampleUse2: "The band's early music was deliberately cacophonous.",
  },
  {
    word: "canonize",
    meaning: "treat like a god; deeply venerate",
    partOfSpeech: "Verb",
    exampleUse1: "The church decided to canonize the martyred priest.",
    exampleUse2: "Fans tend to canonize their favorite musicians.",
  },
  {
    word: "censure",
    meaning: "strongly criticize or disapprove",
    partOfSpeech: "Verb",
    exampleUse1: "The senator was censured for ethical violations.",
    exampleUse2: "The editorial censured the mayor's handling of the crisis.",
  },
  {
    word: "chicanery",
    meaning: "using deception to attain a certain goal",
    partOfSpeech: "Noun",
    exampleUse1: "The election was marred by political chicanery.",
    exampleUse2: "He used legal chicanery to avoid paying taxes.",
  },
  {
    word: "coalesce",
    meaning: "bring elements together; unite",
    partOfSpeech: "Verb",
    exampleUse1: "The rival factions coalesced to oppose the new law.",
    exampleUse2: "Her ideas coalesced into a comprehensive theory.",
  },
  {
    word: "cogent",
    meaning: "persuasive and clear; compelling",
    partOfSpeech: "Adjective",
    exampleUse1: "She presented a cogent argument for policy reform.",
    exampleUse2: "The lawyer's cogent summary convinced the jury.",
  },
  {
    word: "compelling",
    meaning: "persuasive and clear",
    partOfSpeech: "Adjective",
    exampleUse1: "The evidence made a compelling case for conviction.",
    exampleUse2: "His compelling testimony changed many minds.",
  },
  {
    word: "compelling",
    meaning: "attracting interest; fascinating",
    partOfSpeech: "Adjective",
    exampleUse1: "The novel had a compelling plot that kept me reading.",
    exampleUse2: "She has a compelling personality that draws people in.",
  },
  {
    word: "contend",
    meaning: "argue a certain point of view; assert",
    partOfSpeech: "Verb",
    exampleUse1: "The author contends that modern art has lost its way.",
    exampleUse2: "Scientists contend that climate change is accelerating.",
  },
  {
    word: "contend",
    meaning: "compete",
    partOfSpeech: "Verb",
    exampleUse1: "Three teams will contend for the championship.",
    exampleUse2: "She contended against more experienced athletes.",
  },
  {
    word: "contend",
    meaning: "struggle or attempt to overcome something",
    partOfSpeech: "Verb",
    exampleUse1: "The village contended with food shortages after the storm.",
    exampleUse2: "He's contending with serious health issues.",
  },
  {
    word: "copious",
    meaning: "existing in great supply; abundant",
    partOfSpeech: "Adjective",
    exampleUse1: "She took copious notes during the lecture.",
    exampleUse2: "The region receives copious rainfall in spring.",
  },
  {
    word: "cosmopolitan",
    meaning: "(of a city) highly diverse",
    partOfSpeech: "Adjective",
    exampleUse1: "New York is a truly cosmopolitan metropolis.",
    exampleUse2: "The university attracts a cosmopolitan student body.",
  },
  {
    word: "cosmopolitan",
    meaning: "(of a person) sophisticated and urbane",
    partOfSpeech: "Adjective",
    exampleUse1: "His cosmopolitan manners impressed the diplomats.",
    exampleUse2: "After years of travel, she had become quite cosmopolitan.",
  },
  {
    word: "deference",
    meaning: "high regard and respect; esteem",
    partOfSpeech: "Noun",
    exampleUse1: "The young lawyer treated the judge with deference.",
    exampleUse2: "In deference to his age, they let him speak first.",
  },
  {
    word: "desultory",
    meaning: "unplanned; without enthusiasm",
    partOfSpeech: "Adjective",
    exampleUse1: "They made desultory attempts to clean the garage.",
    exampleUse2: "The meeting proceeded in a desultory fashion.",
  },
  {
    word: "diffident",
    meaning: "reserved or shy; without confidence",
    partOfSpeech: "Adjective",
    exampleUse1: "His diffident manner hid a brilliant mind.",
    exampleUse2: "The diffident student rarely spoke in class.",
  },
  {
    word: "dilatory",
    meaning: "slow and unhurried; meant to stall",
    partOfSpeech: "Adjective",
    exampleUse1: "The company used dilatory tactics to avoid payment.",
    exampleUse2: "His dilatory response frustrated those waiting for answers.",
  },
  {
    word: "equivocate",
    meaning: "speak evasively; avoid taking a stance",
    partOfSpeech: "Verb",
    exampleUse1: "Politicians often equivocate when asked difficult questions.",
    exampleUse2: "Don't equivocate - give me a straight answer.",
  },
  {
    word: "polarize",
    meaning: "separate into two opposing groups",
    partOfSpeech: "Verb",
    exampleUse1: "The controversial issue polarized the community.",
    exampleUse2: "Social media tends to polarize political opinions.",
  },
  {
    word: "prodigal",
    meaning: "carelessly wasteful; extravagant",
    partOfSpeech: "Adjective",
    exampleUse1: "His prodigal spending left him in debt.",
    exampleUse2: "The prodigal use of resources couldn't continue.",
  },
  {
    word: "prodigal",
    meaning: "a person who is excessively wasteful",
    partOfSpeech: "Noun",
    exampleUse1: "The prodigal returned home after wasting his inheritance.",
    exampleUse2: "She reformed from being a prodigal to quite frugal.",
  },
  {
    word: "verbose",
    meaning: "excessively talkative; wordy",
    partOfSpeech: "Adjective",
    exampleUse1: "The professor's verbose explanation confused students more.",
    exampleUse2: "Legal documents are often unnecessarily verbose.",
  },
];

export const GROUP_4 = [
  {
    word: "abstain",
    meaning: "avoid taking part in something",
    partOfSpeech: "Verb",
    exampleUse1: "He decided to abstain from voting in the election.",
    exampleUse2:
      "Doctors advise patients to abstain from alcohol before surgery.",
  },
  {
    word: "approbation",
    meaning: "appreciation toward someone",
    partOfSpeech: "Noun",
    exampleUse1: "The film received widespread approbation from critics.",
    exampleUse2:
      "She smiled with satisfaction at the approbation of her peers.",
  },
  {
    word: "cherish",
    meaning: "greatly love or protect something",
    partOfSpeech: "Verb",
    exampleUse1: "She will always cherish the memories of her childhood.",
    exampleUse2: "They cherish their family traditions deeply.",
  },
  {
    word: "corroborate",
    meaning: "lend support to; bolster",
    partOfSpeech: "Verb",
    exampleUse1: "The witness could not corroborate the suspect’s alibi.",
    exampleUse2:
      "Studies corroborate the link between stress and heart disease.",
  },
  {
    word: "disparate",
    meaning: "different or contrasting",
    partOfSpeech: "Adjective",
    exampleUse1:
      "They came from disparate backgrounds but became close friends.",
    exampleUse2:
      "The novel combines disparate elements of fantasy and science fiction.",
  },
  {
    word: "emulate",
    meaning: "imitate someone or something",
    partOfSpeech: "Verb",
    exampleUse1: "She tried to emulate her mentor's dedication to her work.",
    exampleUse2: "Young athletes often emulate their sports heroes.",
  },
  {
    word: "enervate",
    meaning: "sap the energy out of someone; fatigue",
    partOfSpeech: "Verb",
    exampleUse1: "The long meeting enervated everyone in the room.",
    exampleUse2: "A hot climate can enervate even the most energetic people.",
  },
  {
    word: "ephemeral",
    meaning: "extremely short lasting",
    partOfSpeech: "Adjective",
    exampleUse1: "Fame in the digital age is often ephemeral.",
    exampleUse2: "The beauty of the sunset was ephemeral but breathtaking.",
  },
  {
    word: "fervid",
    meaning: "excessively energetic or eager",
    partOfSpeech: "Adjective",
    exampleUse1: "The speaker gave a fervid plea for environmental action.",
    exampleUse2: "Her fervid imagination brought the story to life.",
  },
  {
    word: "garrulous",
    meaning: "tending to talk too much; wordy",
    partOfSpeech: "Adjective",
    exampleUse1: "The garrulous host kept the conversation going all night.",
    exampleUse2:
      "He grew annoyed with the garrulous old man sitting next to him.",
  },
  {
    word: "incendiary",
    meaning: "provocative; causing conflict",
    partOfSpeech: "Adjective",
    exampleUse1: "His incendiary remarks sparked a heated debate.",
    exampleUse2:
      "The article was full of incendiary language meant to provoke outrage.",
  },
  {
    word: "inimical",
    meaning: "damaging; hostile in manner or tone",
    partOfSpeech: "Adjective",
    exampleUse1: "Their relationship became increasingly inimical.",
    exampleUse2: "Such policies are inimical to democratic values.",
  },
  {
    word: "intimate",
    meaning: "subtly suggest or imply",
    partOfSpeech: "Verb",
    exampleUse1: "He intimated that he might retire soon.",
    exampleUse2: "Her tone intimated dissatisfaction with the decision.",
  },
  {
    word: "invigorate",
    meaning: "provide energy or vitality to",
    partOfSpeech: "Verb",
    exampleUse1: "A brisk walk in the morning can invigorate you for the day.",
    exampleUse2: "The new strategy invigorated the company’s sales team.",
  },
  {
    word: "mitigate",
    meaning: "diminish negative feelings or situation",
    partOfSpeech: "Verb",
    exampleUse1: "We need to mitigate the effects of climate change.",
    exampleUse2: "The doctor gave her medication to mitigate the pain.",
  },
  {
    word: "obsolete",
    meaning: "no longer useful; outmoded",
    partOfSpeech: "Adjective",
    exampleUse1: "Typewriters have become obsolete in modern offices.",
    exampleUse2: "The law is considered obsolete and rarely enforced.",
  },
  {
    word: "opaque",
    meaning: "unclear; hard to comprehend",
    partOfSpeech: "Adjective",
    exampleUse1: "His explanation was too opaque to understand.",
    exampleUse2: "The technical jargon made the document opaque to readers.",
  },
  {
    word: "opaque",
    meaning: "not able to be seen through",
    partOfSpeech: "Adjective",
    exampleUse1: "The windows were opaque with steam.",
    exampleUse2: "Frost made the glass completely opaque.",
  },
  {
    word: "paradigmatic",
    meaning: "representing the standard example",
    partOfSpeech: "Adjective",
    exampleUse1:
      "Her career is a paradigmatic example of hard work leading to success.",
    exampleUse2: "The novel became a paradigmatic text of modern literature.",
  },
  {
    word: "pedantic",
    meaning: "overly concerned with (minor) details",
    partOfSpeech: "Adjective",
    exampleUse1: "His pedantic comments slowed the meeting down.",
    exampleUse2: "She has a pedantic habit of correcting everyone’s grammar.",
  },
  {
    word: "placid",
    meaning: "calm; free from activity or irritation",
    partOfSpeech: "Adjective",
    exampleUse1: "The placid lake reflected the sky perfectly.",
    exampleUse2: "He remained placid even during the crisis.",
  },
  {
    word: "polemical",
    meaning: "giving a strong, controversial opinion",
    partOfSpeech: "Adjective",
    exampleUse1:
      "The article was full of polemical criticism of the government.",
    exampleUse2: "His polemical stance alienated some of his supporters.",
  },
  {
    word: "precipitate",
    meaning: "cause to happen",
    partOfSpeech: "Verb",
    exampleUse1: "The incident precipitated a political crisis.",
    exampleUse2: "The resignation precipitated the fall of the government.",
  },
  {
    word: "precipitate",
    meaning: "done quickly or suddenly",
    partOfSpeech: "Adjective",
    exampleUse1: "His decision was precipitate and poorly thought out.",
    exampleUse2: "They made a precipitate withdrawal from the negotiations.",
  },
  {
    word: "profundity",
    meaning: "great wisdom or intelligence",
    partOfSpeech: "Noun",
    exampleUse1: "The profundity of his insights impressed the audience.",
    exampleUse2: "Her speech was full of emotional depth and profundity.",
  },
  {
    word: "prophetic",
    meaning: "able to correctly predict the future",
    partOfSpeech: "Adjective",
    exampleUse1: "His warnings turned out to be prophetic.",
    exampleUse2: "The book’s predictions were eerily prophetic.",
  },
  {
    word: "prudent",
    meaning: "wise in decision-making",
    partOfSpeech: "Adjective",
    exampleUse1: "It's prudent to save money for emergencies.",
    exampleUse2: "She made a prudent investment in real estate.",
  },
  {
    word: "punctilious",
    meaning: "highly concerned with details or manners",
    partOfSpeech: "Adjective",
    exampleUse1: "He was punctilious in observing the rules.",
    exampleUse2: "Her punctilious nature made her a great proofreader.",
  },
  {
    word: "recondite",
    meaning: "obscure and difficult to understand",
    partOfSpeech: "Adjective",
    exampleUse1: "The professor’s lecture was full of recondite concepts.",
    exampleUse2: "His writing is often too recondite for the average reader.",
  },
  {
    word: "scrupulous",
    meaning: "careful with details",
    partOfSpeech: "Adjective",
    exampleUse1: "She kept scrupulous records of every transaction.",
    exampleUse2: "The investigation was scrupulous and thorough.",
  },
  {
    word: "scrupulous",
    meaning: "possessing moral integrity",
    partOfSpeech: "Adjective",
    exampleUse1: "He is known for being scrupulous in all his dealings.",
    exampleUse2: "Her scrupulous honesty won everyone's respect.",
  },
  {
    word: "tranquil",
    meaning: "peaceful; free from activity",
    partOfSpeech: "Adjective",
    exampleUse1: "They enjoyed a tranquil afternoon by the lake.",
    exampleUse2: "The village is a tranquil place far from the city.",
  },
  {
    word: "vacillate",
    meaning: "go back and forth with one's view",
    partOfSpeech: "Verb",
    exampleUse1: "She vacillated between studying medicine and law.",
    exampleUse2: "The government continues to vacillate on the issue.",
  },
];

export const GROUP_5 = [
  {
    word: "aloof",
    meaning: "not warm or friendly; impersonal",
    partOfSpeech: "Adjective",
    exampleUse1: "She remained aloof during the group discussion.",
    exampleUse2: "His aloof attitude made it hard to approach him.",
  },
  {
    word: "clangor",
    meaning: "a disturbingly loud noise",
    partOfSpeech: "Noun",
    exampleUse1: "The clangor of pots and pans echoed through the kitchen.",
    exampleUse2: "The clangor from the construction site was unbearable.",
  },
  {
    word: "conventional",
    meaning: "adhering to established practices or accepted standards",
    partOfSpeech: "Adjective",
    exampleUse1: "She wore a conventional dress to the formal event.",
    exampleUse2: "He prefers conventional methods over experimental ones.",
  },
  {
    word: "debunk",
    meaning: "prove a belief or idea false",
    partOfSpeech: "Verb",
    exampleUse1: "The scientist debunked the myth with evidence.",
    exampleUse2: "The article aims to debunk common misconceptions.",
  },
  {
    word: "diminutive",
    meaning: "exceptionally small in size or stature",
    partOfSpeech: "Adjective",
    exampleUse1: "She was a diminutive figure among the tall players.",
    exampleUse2: "The diminutive car fit easily into the small space.",
  },
  {
    word: "discernible",
    meaning: "able to be recognized or understood",
    partOfSpeech: "Adjective",
    exampleUse1: "There was a discernible difference in tone.",
    exampleUse2: "His accent was barely discernible after years abroad.",
  },
  {
    word: "enigmatic",
    meaning: "hard to understand; mysterious",
    partOfSpeech: "Adjective",
    exampleUse1: "She gave him an enigmatic smile.",
    exampleUse2: "The painting has an enigmatic quality.",
  },
  {
    word: "estranged",
    meaning: "emotionally distanced from someone",
    partOfSpeech: "Adjective",
    exampleUse1: "He felt estranged from his old friends.",
    exampleUse2: "The argument left them emotionally estranged.",
  },
  {
    word: "extravagant",
    meaning: "excessive, especially in terms of cost",
    partOfSpeech: "Adjective",
    exampleUse1: "They threw an extravagant wedding party.",
    exampleUse2: "His taste in clothes is rather extravagant.",
  },
  {
    word: "fanciful",
    meaning: "highly imaginative; unrealistic",
    partOfSpeech: "Adjective",
    exampleUse1: "The story was too fanciful to be believable.",
    exampleUse2: "She had a fanciful idea about traveling through time.",
  },
  {
    word: "frivolous",
    meaning: "lacking in seriousness or importance; silly",
    partOfSpeech: "Adjective",
    exampleUse1: "They wasted money on frivolous purchases.",
    exampleUse2: "His frivolous attitude annoyed the serious team.",
  },
  {
    word: "frivolous",
    meaning: "(of a person) not taking things seriously",
    partOfSpeech: "Adjective",
    exampleUse1: "She's too frivolous to manage such responsibility.",
    exampleUse2: "He was seen as frivolous and unreliable.",
  },
  {
    word: "heterogeneous",
    meaning: "composed of varying, diverse elements",
    partOfSpeech: "Adjective",
    exampleUse1: "The crowd was a heterogeneous mix of people.",
    exampleUse2: "The materials were too heterogeneous to blend well.",
  },
  {
    word: "imperious",
    meaning: "having an arrogant or domineering manner",
    partOfSpeech: "Adjective",
    exampleUse1: "His imperious tone silenced the room.",
    exampleUse2: "She gave imperious orders that no one dared question.",
  },
  {
    word: "impertinent",
    meaning: "disrespectful or inappropriate",
    partOfSpeech: "Adjective",
    exampleUse1: "The student was punished for his impertinent remark.",
    exampleUse2: "She considered his question impertinent.",
  },
  {
    word: "impertinent",
    meaning: "irrelevant or unrelated to something",
    partOfSpeech: "Adjective",
    exampleUse1: "The comment was impertinent to the discussion.",
    exampleUse2: "He kept making impertinent observations.",
  },
  {
    word: "invasive",
    meaning: "infringing on others' privacy",
    partOfSpeech: "Adjective",
    exampleUse1: "She found the reporter’s questions invasive.",
    exampleUse2: "Invasive surveillance raised privacy concerns.",
  },
  {
    word: "invasive",
    meaning: "spreading rapidly and causing harm",
    partOfSpeech: "Adjective",
    exampleUse1: "The invasive species disrupted the ecosystem.",
    exampleUse2: "Invasive plants choked the native vegetation.",
  },
  {
    word: "irresolute",
    meaning: "uncertain or lacking determination",
    partOfSpeech: "Adjective",
    exampleUse1: "He stood irresolute at the crossroads.",
    exampleUse2: "Her irresolute response disappointed the team.",
  },
  {
    word: "laudable",
    meaning: "worthy of admiration or praise",
    partOfSpeech: "Adjective",
    exampleUse1: "Her efforts to help the homeless are laudable.",
    exampleUse2: "He made a laudable attempt to resolve the issue.",
  },
  {
    word: "lax",
    meaning: "not diligent or careful; casual",
    partOfSpeech: "Adjective",
    exampleUse1: "The manager was lax about enforcing deadlines.",
    exampleUse2: "Lax security led to the breach.",
  },
  {
    word: "marginalize",
    meaning: "treat someone or something as insignificant",
    partOfSpeech: "Verb",
    exampleUse1: "The policies marginalized minority groups.",
    exampleUse2: "Artists often feel marginalized by mainstream media.",
  },
  {
    word: "panache",
    meaning: "a stylish and confident manner",
    partOfSpeech: "Noun",
    exampleUse1: "She delivered the speech with great panache.",
    exampleUse2: "He entered the room with flair and panache.",
  },
  {
    word: "plodding",
    meaning: "moving slowly or laboriously",
    partOfSpeech: "Adjective",
    exampleUse1: "The movie had a plodding pace.",
    exampleUse2: "She took a plodding approach to her tasks.",
  },
  {
    word: "prosaic",
    meaning: "straightforward; unoriginal; unimaginative",
    partOfSpeech: "Adjective",
    exampleUse1: "His writing style is prosaic and lacks flair.",
    exampleUse2: "The design is functional but prosaic.",
  },
  {
    word: "remedial",
    meaning: "serving to correct or cure something",
    partOfSpeech: "Adjective",
    exampleUse1: "He was placed in a remedial math class.",
    exampleUse2: "The school offers remedial programs for struggling students.",
  },
  {
    word: "restive",
    meaning: "demonstrating difficulty in staying still",
    partOfSpeech: "Adjective",
    exampleUse1: "The children became restive during the long ceremony.",
    exampleUse2: "The crowd grew restive as the speech dragged on.",
  },
  {
    word: "sporadic",
    meaning: "happening occasionally and irregularly",
    partOfSpeech: "Adjective",
    exampleUse1: "There were sporadic power outages throughout the week.",
    exampleUse2: "Sporadic rainfall delayed the harvest.",
  },
  {
    word: "stigmatize",
    meaning: "label or mark as disgraceful",
    partOfSpeech: "Verb",
    exampleUse1: "Society tends to stigmatize mental illness.",
    exampleUse2: "He was unfairly stigmatized by his past mistakes.",
  },
  {
    word: "undermine",
    meaning: "weaken or sabotage, often subtly",
    partOfSpeech: "Verb",
    exampleUse1: "His actions undermined the team's confidence.",
    exampleUse2: "The scandal undermined her credibility.",
  },
  {
    word: "weary",
    meaning: "feeling tired or exhausted",
    partOfSpeech: "Adjective",
    exampleUse1: "She looked weary after the long journey.",
    exampleUse2: "He grew weary of repeating himself.",
  },
  {
    word: "zealous",
    meaning: "intensely passionate",
    partOfSpeech: "Adjective",
    exampleUse1: "The zealous fans cheered loudly for their team.",
    exampleUse2: "She was zealous in advocating for animal rights.",
  },
];

export const GROUP_6 = [
  {
    word: "admonish",
    meaning: "scold someone seriously",
    partOfSpeech: "Verb",
    exampleUse1:
      "The teacher admonished the students for cheating on the test.",
    exampleUse2: "His mother admonished him for coming home so late.",
  },
  {
    word: "admonish",
    meaning: "give someone urgent advice",
    partOfSpeech: "Verb",
    exampleUse1: "The doctor admonished her to quit smoking immediately.",
    exampleUse2: "I must admonish you to reconsider this risky investment.",
  },
  {
    word: "aesthetic",
    meaning: "pertaining to beauty or the appreciation thereof",
    partOfSpeech: "Adjective",
    exampleUse1: "The museum's aesthetic appeal attracted many visitors.",
    exampleUse2: "She made aesthetic improvements to the garden design.",
  },
  {
    word: "affectation",
    meaning: "a pretense or show meant to impress others",
    partOfSpeech: "Noun",
    exampleUse1: "His British accent was clearly an affectation.",
    exampleUse2: "She saw through his affectation of sophistication.",
  },
  {
    word: "alleviate",
    meaning: "lessen the intensity or severity of something negative",
    partOfSpeech: "Verb",
    exampleUse1: "The medication helped alleviate her chronic pain.",
    exampleUse2: "Volunteers worked to alleviate suffering after the disaster.",
  },
  {
    word: "analogous",
    meaning: "comparable or similar to",
    partOfSpeech: "Adjective",
    exampleUse1: "The structure of an atom is analogous to a solar system.",
    exampleUse2: "Their relationship was analogous to that of siblings.",
  },
  {
    word: "bolster",
    meaning: "lend support or boost",
    partOfSpeech: "Verb",
    exampleUse1: "The new evidence bolstered their case in court.",
    exampleUse2: "She drank coffee to bolster her energy before the meeting.",
  },
  {
    word: "chauvinistic",
    meaning: "excessively patriotic or biased in favor of a group or cause",
    partOfSpeech: "Adjective",
    exampleUse1:
      "His chauvinistic remarks about other countries offended many.",
    exampleUse2:
      "The company was criticized for its chauvinistic hiring practices.",
  },
  {
    word: "connoisseur",
    meaning: "a discerning expert in matters of taste",
    partOfSpeech: "Noun",
    exampleUse1: "As a wine connoisseur, he could identify rare vintages.",
    exampleUse2: "The art connoisseur recognized the forgery immediately.",
  },
  {
    word: "dissemble",
    meaning: "hide or misrepresent one's true feelings or beliefs",
    partOfSpeech: "Verb",
    exampleUse1: "He dissembled his disappointment with a forced smile.",
    exampleUse2:
      "Politicians often dissemble when answering difficult questions.",
  },
  {
    word: "dogged",
    meaning: "demonstrating tenacity and an unwillingness to give up",
    partOfSpeech: "Adjective",
    exampleUse1: "Her dogged determination led to the discovery.",
    exampleUse2: "The detective pursued the case with dogged persistence.",
  },
  {
    word: "dupe",
    meaning: "trick or fool someone",
    partOfSpeech: "Verb",
    exampleUse1: "Scammers duped elderly victims out of their savings.",
    exampleUse2:
      "He felt duped after realizing the product didn't work as advertised.",
  },
  {
    word: "empirical",
    meaning: "based on observation or experience rather than conjecture",
    partOfSpeech: "Adjective",
    exampleUse1: "Scientists rely on empirical evidence to support theories.",
    exampleUse2: "The study provided empirical data about consumer behavior.",
  },
  {
    word: "engender",
    meaning: "produce or stimulate the development of something",
    partOfSpeech: "Verb",
    exampleUse1: "The controversial policy engendered much debate.",
    exampleUse2: "His kindness engendered trust among his colleagues.",
  },
  {
    word: "entitled",
    meaning: "assuming oneself to be deserving of special rights or privileges",
    partOfSpeech: "Adjective",
    exampleUse1: "The entitled customer demanded special treatment.",
    exampleUse2: "His entitled attitude made him unpopular with coworkers.",
  },
  {
    word: "pertinacious",
    meaning: "stubbornly holding onto a belief or course of action",
    partOfSpeech: "Adjective",
    exampleUse1: "Her pertinacious refusal to compromise stalled negotiations.",
    exampleUse2:
      "The pertinacious reporter kept investigating despite obstacles.",
  },
  {
    word: "presumptuous",
    meaning: "overstepping boundaries, often in an overconfident way",
    partOfSpeech: "Adjective",
    exampleUse1: "It was presumptuous of him to speak for the entire group.",
    exampleUse2: "Her presumptuous suggestion offended the senior staff.",
  },
  {
    word: "probity",
    meaning: "the characteristic of having strong ethical standards",
    partOfSpeech: "Noun",
    exampleUse1: "The judge was respected for his unquestionable probity.",
    exampleUse2: "Financial advisors must demonstrate absolute probity.",
  },
  {
    word: "proliferate",
    meaning: "rapidly increase or multiply in number",
    partOfSpeech: "Verb",
    exampleUse1: "Fast food chains continue to proliferate worldwide.",
    exampleUse2: "Online scams proliferated during the pandemic.",
  },
  {
    word: "specious",
    meaning: "seemingly reasonable but actually wrong",
    partOfSpeech: "Adjective",
    exampleUse1: "His specious argument fell apart under scrutiny.",
    exampleUse2: "The advertisement made specious claims about the product.",
  },
  {
    word: "spurious",
    meaning: "not genuine; bogus",
    partOfSpeech: "Adjective",
    exampleUse1: "The museum discovered the painting was a spurious imitation.",
    exampleUse2: "He made spurious accusations without evidence.",
  },
  {
    word: "subjective",
    meaning: "pertaining to personal feelings rather than objective reality",
    partOfSpeech: "Adjective",
    exampleUse1: "Art appreciation is largely subjective.",
    exampleUse2: "Her review contained many subjective opinions.",
  },
  {
    word: "subvert",
    meaning: "undermine or weaken, typically an authority of some sort",
    partOfSpeech: "Verb",
    exampleUse1: "The rebels sought to subvert the government.",
    exampleUse2: "The parody subtly subverted traditional gender roles.",
  },
  {
    word: "timorous",
    meaning: "displaying nervousness; lacking confidence",
    partOfSpeech: "Adjective",
    exampleUse1: "The timorous intern hesitated to share her ideas.",
    exampleUse2: "His timorous approach to negotiations weakened his position.",
  },
  {
    word: "tortuous",
    meaning: "marked by numerous twists or turns",
    partOfSpeech: "Adjective",
    exampleUse1: "The tortuous mountain road made driving difficult.",
    exampleUse2: "They followed the tortuous path through the dense forest.",
  },
  {
    word: "tortuous",
    meaning: "overly complicated and long",
    partOfSpeech: "Adjective",
    exampleUse1: "The contract's tortuous language confused many signers.",
    exampleUse2: "The approval process became tortuous with added regulations.",
  },
  {
    word: "tractable",
    meaning: "easily managed or controlled",
    partOfSpeech: "Adjective",
    exampleUse1: "The tractable horse was perfect for beginner riders.",
    exampleUse2: "She found the students remarkably tractable after lunch.",
  },
  {
    word: "tractable",
    meaning: "(of a situation) easy to solve or handle",
    partOfSpeech: "Adjective",
    exampleUse1: "The math problem proved surprisingly tractable.",
    exampleUse2:
      "What seemed like a crisis became tractable with proper analysis.",
  },
  {
    word: "transient",
    meaning: "not lasting, enduring, or permanent; transitory",
    partOfSpeech: "Adjective",
    exampleUse1: "The drug's effects were powerful but transient.",
    exampleUse2: "They enjoyed the transient beauty of the cherry blossoms.",
  },
  {
    word: "ubiquitous",
    meaning: "being everywhere at once",
    partOfSpeech: "Adjective",
    exampleUse1: "Smartphones have become ubiquitous in modern society.",
    exampleUse2:
      "The ubiquitous advertising made the product instantly recognizable.",
  },
  {
    word: "underscore",
    meaning: "emphasize or show the importance of something",
    partOfSpeech: "Verb",
    exampleUse1: "The report underscores the need for immediate action.",
    exampleUse2: "Her speech underscored the values of equality and justice.",
  },
  {
    word: "venal",
    meaning: "open to bribery or corruption",
    partOfSpeech: "Adjective",
    exampleUse1: "The venal official accepted bribes for political favors.",
    exampleUse2: "The investigation revealed a venal system of kickbacks.",
  },
  {
    word: "venerate",
    meaning: "regard with deep respect or reverence",
    partOfSpeech: "Verb",
    exampleUse1: "Many cultures venerate their ancestors.",
    exampleUse2:
      "The scientist was venerated for her groundbreaking discoveries.",
  },
];

// Export all groups in an object for easy access
export const ALL_GROUPS = {
  "Group 1": GROUP_1,
  "Group 2": GROUP_2,
  "Group 3": GROUP_3,
  "Group 4": GROUP_4,
  "Group 5": GROUP_5,
  "Group 6": GROUP_6,
};
